apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sptribs-frontend
spec:
  values:
    nodejs:
      image: hmctsprod.azurecr.io/sptribs/frontend:prod-f2d4382-20260716150902
      environment:
        PCQ_ENABLED: false
        RATE_LIMITER_DISABLED: true
        IDAM_API_URL: https://idam-api.demo.platform.hmcts.net/o/token
        IDAM_WEB_URL: https://idam-web-public.demo.platform.hmcts.net/login