apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sptribs-frontend
spec:
  values:
    nodejs:
      image: hmctsprod.azurecr.io/sptribs/frontend:pr-1066-cc2031c-20260515150344
      environment:
        PCQ_ENABLED: false
