apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sptribs-frontend
spec:
  values:
    nodejs:
      image: hmctsprod.azurecr.io/sptribs/frontend:pr-1062-9bbd759-20260513100836
      environment:
        PCQ_ENABLED: false
