apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sptribs-frontend
spec:
  values:
    nodejs:
      image: hmctsprod.azurecr.io/sptribs/frontend:pr-1066-70cbac0-20260716162325
      environment:
        IDAM_API_URL: https://idam-web-public.perftest.platform.hmcts.net/o/token
        IDAM_WEB_URL: https://idam-web-public.perftest.platform.hmcts.net/o/authorize
        IDAM_HMCTS_URL: https://hmcts-access.perftest.platform.hmcts.net
        IDAM_END_SESSION_URL: 'https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/o/endSession'
        PCQ_ENABLED: false