apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wa-task-management-api
spec:
  values:
    java:
      memoryRequests: "3072Mi"
      cpuRequests: "3000m"
      memoryLimits: "4096Mi"
      cpuLimits: "4000m"
      environment:
        LOGGING_LEVEL_UK_GOV_HMCTS: DEBUG
        TEMP_FLAG: false
        ALLOWED_JURISDICTIONS: wa,ia,sscs,civil,publiclaw,privatelaw,st_cic,employment,sscs,divorce
        ALLOWED_CASE_TYPES: asylum,wacasetype,sscs,civil,generalapplication,care_supervision_epo,prlapps,criminalinjuriescompensation,et_englandwales,et_scotland,benefit,financialremedycontested,financialremedymvp2,finrem_exceptionrecord,privatelaw_exceptionrecord,bail
        SPRING_PROFILES_ACTIVE: "replica"
        MANDATORY_TASK_FIELD_CHECK_ENABLED: true
        IDAM_SECURITY_ALLOWED_ISSUER_0: https://idam-web-public.aat.platform.hmcts.net/o
        IDAM_SECURITY_ALLOWED_ISSUER_1: https://hmcts-access.aat.platform.hmcts.net/o
        IDAM_SECURITY_ALLOWED_ISSUER_2: https://forgerock-am.service.core-compute-idam-aat2.internal:8443/openam/oauth2/realms/root/realms/hmcts
        WA_S2S_AUTHORIZED_SERVICES: ccd,ccd_data,ccd_gw,ccd_ps,iac,wa_task_management_api,xui_webapp,wa_task_monitor,camunda_bpm,wa_workflow_api,wa_case_event_handler,ccd_case_disposer,civil_service,sscs,prl_cos_api
