apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ia-case-documents-api
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/ia/case-documents-api:prod-fe2799c-20260701154858 #{"$imagepolicy": "flux-system:ithc-ia-case-documents-api"}
      environment:
        DUMMY: false
