apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ia-case-documents-api
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/ia/case-documents-api:prod-d0aa96e-20260316141359 #{"$imagepolicy": "flux-system:ithc-ia-case-documents-api"}
      environment:
        DUMMY: true
