apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ia-case-documents-api
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/ia/case-documents-api:prod-6f58ee7-20260914085646 #{"$imagepolicy": "flux-system:perftest-ia-case-documents-api"}
      environment:
        RESTART_PODS: "Y"
