apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ia-case-documents-api
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/ia/case-documents-api:prod-6cd0fac-20260526103047 #{"$imagepolicy": "flux-system:perftest-ia-case-documents-api"}
