apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apim-marketplace-web
spec:
  values:
    nodejs:
      ingressHost: apim-marketplace-web.aat.platform.hmcts.net
      keyVaults:
        apim:
          secrets:
            - name: marketplace-web-redis-host
              alias: REDIS_HOST
            - name: marketplace-web-redis-port
              alias: REDIS_PORT
            - name: marketplace-web-redis-access-key
              alias: REDIS_KEY
            - name: marketplace-web-session-secret
              alias: SESSION_SECRET
