apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: apim-marketplace-web
  annotations:
    hmcts.github.com/image-registry: hmctsprod
spec:
  image: hmctsprod.azurecr.io/apim/marketplace-web
