apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apim-marketplace-web
spec:
  values:
    nodejs:
      ingressHost: apim-marketplace-web-sandbox.service.core-compute-sandbox.internal
