apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: restart-pods
  namespace: admin
spec:
  values:
    image: hmctsprod.azurecr.io/hmcts-kubectl/kubectl:prod-e29b17f7-1772453743
