apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: probate-back-office
  namespace: probate
spec:
  values:
    java:
      environment:
        CCD_GATEWAY_HOST: https://manage-case.aat.platform.hmcts.net
        # Does what it says on the tin - if this changes then aat should redeploy
        CHANGE_TO_REDEPLOY_AAT: 20251215
        PROBATE_POSTGRESQL_USER: pgadmin
        PROBATE_POSTGRESQL_HOSTNAME: probatemandb-postgres-flexible-db-aat.postgres.database.azure.com
        PROBATE_POSTGRESQL_PORT: 5432