apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: probate-back-office
  namespace: probate
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/probate/back-office:pr-3770-c270c7e-20260519131545 #{"$imagepolicy": "flux-system:demo-probate-back-office"}
      environment:
        CCD_GATEWAY_HOST: https://manage-case.demo.platform.hmcts.net
        PROBATE_POSTGRESQL_USER: pgadmin
        PROBATE_POSTGRESQL_HOSTNAME: probatemandb-postgres-flexible-db-demo.postgres.database.azure.com
        PROBATE_POSTGRESQL_PORT: 5432
        EXCEPTED_ESTATE_DATE_OF_DEATH: "2022-01-01"
        BLOB_STORAGE_SMEEANDFORD_FEATURE_ENABLED: true
        CASE_DOCUMENT_AM_URL: http://ccd-case-document-am-api-demo.service.core-compute-demo.internal
        IDAM_SERVICE_HOST: https://idam-api.demo.platform.hmcts.net
        BACK_OFFICE_BASEURL: http://probate-back-office-demo.service.core-compute-demo.internal
        ACA_SERVICE_API_BASEURL: http://aac-manage-case-assignment-demo.service.core-compute-demo.internal
        # Does what it says on the tin - if this changes then demo should redeploy
        CHANGE_TO_REDEPLOY_DEMO: 20260511
        MANAGE_CASE_URL: https://manage-case.demo.platform.hmcts.net/cases/case-details/<CASE_ID>
        FRONTEND_URL: https://probate.demo.platform.hmcts.net/get-case/<CASE_ID>?probateType=<CASE_TYPE>