apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: probate-back-office
  namespace: probate
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/probate/back-office:pr-3630-241ffdb-20260610110648 #{"$imagepolicy": "flux-system:ithc-probate-back-office"}
      environment:
        CCD_GATEWAY_HOST: https://gateway-ccd.ithc.platform.hmcts.net
        PROBATE_POSTGRESQL_USER: pgadmin
        PROBATE_POSTGRESQL_HOSTNAME: probatemandb-postgres-flexible-db-ithc.postgres.database.azure.com
        PROBATE_POSTGRESQL_PORT: 5432
        # Does what it says on the tin - if this changes then ithc should redeploy
        CHANGE_TO_REDEPLOY_ITHC: 20251215
