apiVersion: v1
data:
  values.yaml: ENC[AES256_GCM,data:4QhAjEBbRKr0GxgYHIcvWcERaONIoZUzK/Br9O8cAoinU+5SuuODl08nPg6jtkBK09iGl0cdT3BWxATOTS9uY2JUMtvT7jMsTlcqRA6RPMZPt/VgDZSv+gLMeLmmNmBTOEFE/ccERXu/Jlgoank2DpJPKWz+KKAkdPxwq070mEXSBEWGPowq4V74DU3y8i+D2iRHN1Hk1ad0pwZ0GBoQbaDX81kN1cbSslL9cMKAF2MVCXwU5oL/+qwSTIxx9MKfEhX/6lO2Lpg7clMLBxTtMtETYsArnqmtg7Etgur8nSxz60sUbj0rWPLHOG/FABvJdQpp96gjZE7p4LsG1Ly78ACKpceF1y6XwnLsvLr7ANleim/D3D/CEFWbHeJMssWrGMQRcxljZs5Ow4JU8YNCcygVguDWY/X/YDttQbBladV8AGto4pFkf5kr965Uf4h5pV/O2EYrS75/9vNv3bnCJDs6RmGoZK32UjnccFYt3HyjZEHjMLDn1YFpuuEVgbsLwKTuZnwQD9dRmxTdAvGbXAYA7oSbrracLf2sWA==,iv:c5RFa/AzL9lZO/W2IP2VjROFqqH/vvezHyhnmPznrds=,tag:1keIYo4CBbHrZhMqimLOlA==,type:str]
kind: Secret
metadata:
  name: opentelemetry-values
  namespace: monitoring
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv:
    - vault_url: https://dtscftptlsbox.vault.azure.net
      name: sops-key
      version: b8a4ffea7a5041318ec2d7623a298d0c
      created_at: "2026-08-18T12:21:22Z"
      enc: BDLezORU7iK0XSRmcdf7m0Wm54Wf-HI90bhdE-iyoiK-U5UCTJKxQubWVJkJ48nq5yL-Prk_1NLNR0WMW4_uwR3G_qebHaIaG3xtLcccwQHdkafC3d2tM9Lj1T9Fbpn5QWli9HqqTL_Ijap0-KNbCsCClxv5FvjHA6bY8ukSVa2_YqJhYpxCd4PO9h7qv4jyvgAvbWNMmbIzuZKAJUGrU8SqzX205S0CYQ65M2-a9CluZTJfvAd_SSUxM4HF5doYS3uL_CZX6Zh7RtJZDWziwlGnK-BD8FtlqKg5ddosXnZfWrR4JMvnwJAR3EfVQbI5d1KPl0giqPWiNylswdWBUQ
  hc_vault: []
  age: []
  lastmodified: "2026-08-18T12:21:23Z"
  mac: ENC[AES256_GCM,data:bVD4LH/6rlRDR7D38ICL32+RZwYIHrp5l8+swY6jjmaCz5F0tCySsAcn6ayZVjc4uhHxCnmg817FT2wjbWf7USOvem4uzfQ2UKdJfa6SFBNnkegPpkyIfCxdG31A077CxJm0pwcE/cTzuCPY9gd8a6dw4JJO308U/DxcSbznF6E=,iv:GVTYx55wmQMYUWErHW8OmoVzICfg3aOhhOTvnpvp1no=,tag:KwP0KmOhPjL8ABwG8POGGg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
