apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fact-api
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/fact/api:prod-9542d62-20260729095331
      imagePullPolicy: Always
