apiVersion: dynatrace.com/v1beta5
kind: DynaKube
metadata:
  name: dynakube
  namespace: dynatrace
spec:
  apiUrl: https://yrk32651.live.dynatrace.com/api
  oneAgent:
    cloudNativeFullStack:
      annotations:
        cluster-autoscaler.kubernetes.io/enable-ds-eviction: "false"
      args:
        - --set-host-group=PREVIEW_CFT
  activeGate:
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 2000m
        memory: 4Gi
