apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ia-hearings-api
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/ia/hearings-api:prod-f8e666e-20260707154153 #{"$imagepolicy": "flux-system:ia-hearings-api"}
      environment:
        DUMMY: "true"
