apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wa
resources:
- ../base
patches:
- path: ../../wa-task-batch-reconfiguration/perftest.yaml
- path: ../../wa-task-batch-termination/perftest.yaml
- path: ../../wa-task-batch-initiation/perftest.yaml
- path: ../../wa-task-batch-update-search-index/perftest.yaml
- path: ../../wa-task-batch-replication-check/perftest.yaml
