apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

patches:
- path: ../../../apps/flux-system/perftest/01/kustomize.yaml
- target:
    kind: Kustomization
    name: xui
  patch: |-
    - op: replace
      path: /spec/path
      value: ./apps/xui/perftest/01
