apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: ccd
data:
  ES_HOST0: http://ccd-data-0.service.core-compute-prod.internal:9200
  ES_HOST1: http://ccd-data-1.service.core-compute-prod.internal:9200
  ES_HOST2: http://ccd-data-2.service.core-compute-prod.internal:9200
  ES_HOST3: http://ccd-data-3.service.core-compute-prod.internal:9200