apiVersion: v1
kind: ServiceAccount
metadata:
  name: dtsse-agent-hub-orchestrator
  namespace: ${NAMESPACE}
  annotations:
    azure.workload.identity/client-id: "3f8d011c-c955-405a-b348-53a961b85b4b"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dtsse-agent-hub-orchestrator
  namespace: ${NAMESPACE}
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "create", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dtsse-agent-hub-orchestrator
  namespace: ${NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dtsse-agent-hub-orchestrator
subjects:
  - kind: ServiceAccount
    name: dtsse-agent-hub-orchestrator
    namespace: ${NAMESPACE}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtsse-agent-hub-orchestrator
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: dtsse-agent-hub-orchestrator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dtsse-agent-hub-orchestrator
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: dtsse-agent-hub-orchestrator
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: orchestrator
          image: hmctsprod.azurecr.io/dtsse/agent-hub:prod-34a76db-20261005162925 #{"$imagepolicy": "flux-system:dtsse-agent-hub"}
          command: ["node", "dist/cli/orchestrator.js"]
          env:
            - name: ORCHESTRATOR_CLUSTER
              value: cft-${CLUSTER_FULL_NAME}
            - name: VIRTUAL_AGENT_IMAGE
              value: hmctsprod.azurecr.io/cft-workspace/devcontainer@sha256:61fa0e0a34b59099694652e4de6820ab739b97cf73c6d3fc4b76d05f52884f3c
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8080
            periodSeconds: 30
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
