apiVersion: v1
kind: ServiceAccount
metadata:
  name: dtsse-agent-hub-orchestrator
  namespace: ${NAMESPACE}
  annotations:
    azure.workload.identity/client-id: "ORCHESTRATOR_CLIENT_ID"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dtsse-agent-hub-virtual-agent
  namespace: ${NAMESPACE}
automountServiceAccountToken: false
