apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ts-translation-service
spec:
  releaseName: ts-translation-service
  values:
    java:
      image: hmctsprod.azurecr.io/ts/translation-service:prod-9de3947-20260521170407 #{"$imagepolicy": "flux-system:demo-ts-translation-service"}
      environment:
        DUMMY_RESTART_VAR: 2
