apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plum-recipe-backend
spec:
  values:
    java:
      ingressHost: plum-recipe-backend-demo.service.core-compute-demo.internal
      image: hmctsprod.azurecr.io/plum/recipe-backend:prod-64a67da-20260518131615 # {"$imagepolicy": "flux-system:plum-recipe-backend"}
