apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plum-recipe-backend
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/plum/recipe-backend:pr-1335
      ingressHost: plum-recipe-backend-sandbox.service.core-compute-sandbox.internal
