apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bp-cron-trigger-daily-processing
spec:
  values:
    job:
      # pr-73 image for testing
      image: hmctsprod.azurecr.io/bulk-scan/cron-trigger:pr-73
      imagePullPolicy: Always
      environment:
        TRIGGER_ENABLED: true
