apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ccpay-callback-function
spec:
  values:
    function:
      image: hmctsprod.azurecr.io/ccpay/callback-function:pr-204-1dee015-20260604152129 #{"$imagepolicy": "flux-system:demo-ccpay-callback-function"}
      aadIdentityName: ccpay
      environment:
        S2S_URL: http://rpe-service-auth-provider-demo.service.core-compute-demo.internal
        MICROSERVICE_PAYMENT_APP: "payment_app"
        SERVICE_LOGGING_ENABLED: false
        SERVICE_CALLBACK_URL_PATTERN: "^https?://(?:[a-z0-9-]+-(aat|prod|demo|ithc|perftest)\\.service\\.core-compute-\\1\\.internal|(?:www\\.)?(?:apply-divorce|end-civil-partnership)\\.service\\.gov\\.uk|[a-z0-9-]+\\.preview\\.platform\\.hmcts\\.net)(?:/.*)?$"
        DUMMY_RESTART_VAR: false
      keyVaults:
        "ccpay":
          secrets:
            - payment-s2s-secret
