---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: neuvector
  namespace: neuvector
spec:
  values:
    neuvector:
      controller:
        azureFileShare:
          # shareName: neuvector-data-01
          shareName: neuvector-data-01-refresh
        ingress:
          host: cft-neuvector01-api.ithc.platform.hmcts.net
        configmap:
          data:
            samlinitcfg.yaml: |
              SSO_URL: https://login.microsoftonline.com/531ff96d-0ae9-462a-8d2d-bec7c0b42082/saml2
              Issuer: https://sts.windows.net/531ff96d-0ae9-462a-8d2d-bec7c0b42082/
              X509_Cert: |
                -----BEGIN CERTIFICATE-----
                MIICxDCCAaygAwIBAgIIecokNzuRzO4wDQYJKoZIhvcNAQELBQAwIjEgMB4GA1UEAwwXQ0ZUIE5l
                dXZlY3RvciAtIElUSEMgMDEwHhcNMjYwNDIyMDg0OTE5WhcNMjcwNDIyMDg1OTE5WjAiMSAwHgYD
                VQQDDBdDRlQgTmV1dmVjdG9yIC0gSVRIQyAwMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
                ggEBANphfUNsE5zVDrz2vQj8qRPQLbw/MZziDdzGjN7owHA/AyqGC3bctX7M8oTZzuHTwnnY9Q2K
                W+zSn81fsUN5+f2ssigSXvgnYqfWMYifLRvqVO27ePkwNJbLTo1x0ooK6Za6wd5CCbB4S7nc7bjf
                lr6UuIaYg63mjrPWmrVXNVnrbLM5h2tFESWvXYyZoOiSa1Q0cpvK2Y4dxbQVgDgDLpLj6ubpipxh
                VsmKFcl0xjlhFHofmhookxN1jrat7alkIDSrAtAgJCvttHt5jmx0fCerhjrFdcECezBZ3dXxMiZx
                HTQVeVmhL6eAwGsuh6Use0TmpWkbWHSW8Avzlf4zeGcCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEA
                k3U7WvKRJEjmUO7zanmmePft0KxA3/+HGQdlMBCAQzK/3jO8wQCGhnnVHIgIb+Tbcy7FF2k7ewb3
                h3wEuXcD3Wp7kfzI1O0ttU2kgnfPVZy3AXHNGpechQEY8Ljimg1rpZ39Bwr2SjvPyqzVjb05Tdh2
                3Kxl/ssEHJKWew2oYiRQmCqyw8aEV5MkqwWb1DakbH4209eJ895gQdND6cqF5dGx7g6zxSHhknp/
                xH0S11F4n64TKSVQRhNCzQTRp4wNHlfltTi/cDfBHW/kWCa19oNarLAnb5pQirrHf1GbcDn5yMqJ
                9Ey0JBw2HtdKCczxeZR6KpXoTEH0tRv8L98CXA==
                -----END CERTIFICATE-----
              Enable: true
              Default_Role: reader
              Role_Groups:
                admin:
                  - e7ea2042-4ced-45dd-8ae3-e051c6551789
      manager:
        ingress:
          host: cft-neuvector-ithc01.hmcts.net
