apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: repl-docmosis-service
  namespace: ethos
spec:
  releaseName: repl-docmosis-service
  values:
    java:
      image: hmctsprod.azurecr.io/ethos/repl-docmosis-backend:prod-f0b2791-20260416143256 #{"$imagepolicy": "flux-system:repl-docmosis-service"}
      environment:
        DB_QUEUE_ENABLED: true
