apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: repl-docmosis-service
  namespace: ethos
spec:
  releaseName: repl-docmosis-service
  values:
    java:
      image: hmctsprod.azurecr.io/ethos/repl-docmosis-backend:prod-04c9b95-20260408090623 #{"$imagepolicy": "flux-system:repl-docmosis-service"}
