apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: repl-docmosis-service
  namespace: ethos
spec:
  releaseName: repl-docmosis-service
  values:
    java:
      image: hmctsprod.azurecr.io/ethos/repl-docmosis-backend:prod-f62528f-20260415135739 #{"$imagepolicy": "flux-system:repl-docmosis-service"}
