apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: repl-docmosis-service
  namespace: ethos
spec:
  releaseName: repl-docmosis-service
  values:
    java:
      image: hmctsprod.azurecr.io/ethos/repl-docmosis-backend:prod-ffd9c96-20260601094953 #{"$imagepolicy": "flux-system:repl-docmosis-service"}
