apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: probate-cron-ccd-data-migration-tool
spec:
  releaseName: probate-cron-ccd-data-migration-tool
  values:
    job:
      image: hmctsprod.azurecr.io/probate/cron-ccd-data-migration-tool:pr-293-1ba1038-20260305085140 #{"$imagepolicy": "flux-system:demo-cron-ccd-data-migration-tool"}
      schedule: "0 14 31 2 *"
      environment:
        PRD_API_URL: http://rd-professional-api-demo.service.core-compute-demo.internal
        TRIG: trig-2
        CASE_REFERENCES: load_from_csv
        ROLLBACK_CASEREFERENCES: true
        MIGRATION_USE_REIMPL: true
        MIGRATION_ID: "DTSPB-5005_rollback"
        USER_TOKEN_REFRESH_MARGIN_MINS: 5
        S2S_TOKEN_REFRESH_MARGIN_MINS: 5
        MIGRATION_CASES_TO_RESTRICT_TO: "1769017002278029:GrantOfRepresentation,1761235214163072:GrantOfRepresentation,1751543799976582:Caveat,1751544793374063:Caveat,1769016679214333:Caveat"
        DTSPB_5005_QUERY_SIZE: 10
        DTSPB_5005_DRY_RUN: false
        DTSPB_5005_ROLLBACK_DATE: "2026-03-06"
