apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: probate-cron-ccd-data-migration-tool
spec:
  releaseName: probate-cron-ccd-data-migration-tool
  values:
    job:
      image: hmctsprod.azurecr.io/probate/cron-ccd-data-migration-tool:prod-26264b3-20260521085400 #{"$imagepolicy": "flux-system:demo-cron-ccd-data-migration-tool"}
      schedule: "50 8 27 5 *"
      environment:
        PRD_API_URL: http://rd-professional-api-demo.service.core-compute-demo.internal
        TRIG: trig-2
        MIGRATION_USE_REIMPL: true
        MIGRATION_ID: "DTSPB-5005"
        USER_TOKEN_REFRESH_MARGIN_MINS: 5
        S2S_TOKEN_REFRESH_MARGIN_MINS: 5
        DTSPB_5005_ROLLBACK_DATE: "2026-05-26"
        MIGRATION_DRYRUN: true
        DTSPB_5472_ROLLBACK_DATE: "2026-05-07"
