apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
  - ../../../base/workload-identity
  - ../../../azureserviceoperator-system/resources/resource-group.yaml
  - ../../../azureserviceoperator-system/resources/flexibleserver-postgres.yaml
  - ../../../azureserviceoperator-system/resources/flexibleserver-postgres-config.yaml
  - ../sops-secrets
namespace: pt
patches:
  - path: ../aso/pt-postgres.yaml
  - path: ../../serviceaccount/aat.yaml
