apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pcq-consolidation-service
spec:
  values:
    job:
      image: hmctsprod.azurecr.io/pcq/consolidation-service:prod-7a79562-20260710170808 #{"$imagepolicy": "flux-system:demo-pcq-consolidation-service"}
      schedule: "0/15 * * * *"
