apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: dtsse-agent-hub
  annotations:
    hmcts.github.com/image-registry: hmctsprod
spec:
  image: hmctsprod.azurecr.io/dtsse/agent-hub
