apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wa-task-monitor
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/wa/task-monitor:pr-661-71be7fb-20260528152322 #{"$imagepolicy": "flux-system:demo-wa-task-monitor"}
      environment:
        LOGGING_LEVEL_UK_GOV_HMCTS: DEBUG
        RECONFIGURATION_RETRY_WINDOW_TIME_HOURS: 4
