apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wa-task-monitor
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/wa/task-monitor:prod-3b8dbe9-20260615100610 #{"$imagepolicy": "flux-system:ithc-wa-task-monitor"}
      environment:
        REFRESH_FLAG: ""
        LOGGING_LEVEL_UK_GOV_HMCTS: DEBUG
