apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
<<<<<<<< HEAD:apps/sptribs/sptribs-cron-trigger-system-clean-documents/image-repo.yaml
  name: sptribs-cron-trigger-system-clean-documents
========
  name: sptribs-cron-clean-further-documents
>>>>>>>> 2c100e80f858d266a3e6345f1939b5462c1bf093:apps/sptribs/sptribs-cron-clean-further-documents/image-repo.yaml
spec:
  image: hmctspublic.azurecr.io/sptribs/case-api
