apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../labs-debolina-seal/image-repo.yaml
  - ../labs-debolina-seal/image-policy.yaml
  - ../labs-Ibrahimelsanosi-moj/image-repo.yaml
  - ../labs-Ibrahimelsanosi-moj/image-policy.yaml
