apiVersion: v1
kind: ServiceAccount
metadata:
  name: dtsse-services
  namespace: ${NAMESPACE}
  annotations:
    azure.workload.identity/client-id: "5562dfd3-1f42-482b-b18b-6278ab2c14c6"
imagePullSecrets:
  - name: dockerhub-creds
