apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: probate-submit-service
  namespace: probate
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/probate/submit-service:pr-1438-6911b14-20260601134429 #{"$imagepolicy": "flux-system:demo-probate-submit-service"}
      environment:
        # Does what it says on the tin - if this changes then demo should redeploy
        CHANGE_TO_REDEPLOY_DEMO: 20251215
