apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ccpay-paymentoutcome-web
spec:
  values:
    nodejs:
      replicas: 2
      useInterpodAntiAffinity: true
      image: hmctsprod.azurecr.io/ccpay/paymentoutcome-web:prod-d1edd6f-20260327182620 #{"$imagepolicy": "flux-system:demo-ccpay-paymentoutcome-web"}
      imagePullPolicy: Always
      environment:
        DUMMY_VARIABLE: false
