apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pcs-api
spec:
  values:
    java:
      environment:
        HASH_PINS_ENABLED: "false"
        ENABLE_TESTING_SUPPORT: "true"
        PCS_FRONTEND_URL: "https://pcs.aat.platform.hmcts.net"
        BULK_PRINT_SCHEDULE: "FIXED_DELAY|1800s"
        BULK_PRINT_LOOKBACK_HOURS: "1"
