apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pcs-api
spec:
  values:
    java:
      environment:
        HASH_PINS_ENABLED: "false"
        DB_SCHEDULER_EXECUTOR_ENABLED: "false"
