apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pcs-api
spec:
  values:
    java:
      environment:
        HASH_PINS_ENABLED: "false"
        ENABLE_TESTING_SUPPORT: "true"
        PCS_FRONTEND_URL: "https://pcs.aat.platform.hmcts.net"
        BULK_PRINT_SCHEDULE: "FIXED_DELAY|1800s"
        BULK_PRINT_LOOKBACK_HOURS: "1"
        MANAGE_CASE_BASE_URL: "https://manage-case.aat.platform.hmcts.net"
        NOTIFY_TEMPLATE_RESPONSE_NO_COUNTERCLAIM: "5abcd184-3409-41de-b13c-83b5f1e2469d"
        NOTIFY_TEMPLATE_RESPONSE_NO_COUNTERCLAIM_LEGAL_REP: "ae3cb187-5862-4c07-a7c4-589bc3aab2d9"
        NOTIFY_TEMPLATE_COUNTERCLAIM_PAYMENT_REQUIRED: "b7c7e5b1-cd73-49cd-9c71-eb4fe16b0ddf"
        NOTIFY_TEMPLATE_COUNTERCLAIM_PAYMENT_REQUIRED_LEGAL_REP: "eb29b8e7-5a17-445e-b2b6-f9d11cdc71ad"
        NOTIFY_TEMPLATE_COUNTERCLAIM_PAYMENT_SUCCESS: "472e9d65-d496-4421-978e-2e7a733ce064"
        NOTIFY_TEMPLATE_COUNTERCLAIM_PAYMENT_SUCCESS_LEGAL_REP: "7183c87e-466f-4559-b5ac-e58432c4b071"
        NOTIFY_TEMPLATE_COUNTERCLAIM_NO_PAYMENT_REQUIRED: "cf320c6a-c797-4a9f-ace2-e93c8c795809"
        NOTIFY_TEMPLATE_MAKE_A_CLAIM_SAVED_FOR_LATER: "05b820d3-5887-4f4f-adf8-07e32d3a4caa"
        NOTIFY_TEMPLATE_MAKE_A_CLAIM_DEFENDANT_MADE_COUNTERCLAIM: "1b9a51dc-dabc-4cad-a9f2-76181266b9fd"
        NOTIFY_TEMPLATE_MAKE_A_CLAIM_DEFENDANT_RESPONSE_RECEIVED: "33696528-2c19-462b-b879-b7546184953e"
        NOTIFY_TEMPLATE_MAKE_A_CLAIM_ISSUED: "18835d17-afbe-409d-8f03-e89dfd51c7f9"
        NOTIFY_TEMPLATE_GENERAL_APPLICATION_RECEIVED: "fa721ba0-18ab-4018-a2fa-e55056f2c847"
        NOTIFY_TEMPLATE_COUNTERCLAIM_NOT_SUBMITTED_YET: "6cef5d05-3ae3-4487-8eec-75029bc4bfe2"
        NOTIFY_TEMPLATE_NOTICE_OF_CHANGE_COMPLETED: "fc9416ba-9b8e-43ce-ab11-9e9a07946e61"
        NOTIFY_TEMPLATE_NOTICE_OF_CHANGE_COMPLETE_LEGAL_REP: "b121bc29-d5f7-4ed4-9cbc-89fdc13c977c"
        NOTIFY_TEMPLATE_NOTICE_OF_CHANGE_NO_LONGER_REPRESENTING: "b5223559-6419-4849-a609-aac606b17a86"
        NOTIFY_TEMPLATE_NOTICE_OF_CHANGE_OTHER_PARTY_REPRESENTED: "f7963e8e-c868-42fe-9367-0038552ca851"
