apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pcs-api
spec:
  values:
    image: hmctsprod.azurecr.io/pcs/api:prod-551477a-20260706123947 #{"$imagepolicy": "flux-system:demo-pcs-api"}
    java:
      environment:
        HASH_PINS_ENABLED: "false"
        ENABLE_TESTING_SUPPORT: "true"
