apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pcs-api
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/pcs/api:prod-dc10f6e-20260902080125 #{"$imagepolicy": "flux-system:perftest-pcs-api"}
      environment:
        HASH_PINS_ENABLED: "false"
        ENABLE_TESTING_SUPPORT: "true"
        PCS_FRONTEND_URL: "https://pcs.perftest.platform.hmcts.net"
