apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pcs-api
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/pcs/api:prod-11d5068-20260901073836 #{"$imagepolicy": "flux-system:perftest-pcs-api"}
      environment:
        HASH_PINS_ENABLED: "false"
        ENABLE_TESTING_SUPPORT: "true"
