apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pcs-api
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/pcs/api:pr-2179-3938f19-20260821112220 #{"$imagepolicy": "flux-system:pcs-api"} 
      environment:
        HASH_PINS_ENABLED: "false"
        ENABLE_TESTING_SUPPORT: "true"
