apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pcs-api
  namespace: pcs
spec:
  values:
    java:
      environment:
        IDAM_API_URL: https://idam-api.platform.hmcts.net
