apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pcs-api
spec:
  values:
    java:
      cpuRequests: "500m" 
      cpuLimits: "1500m"    
      memoryRequests: "2Gi"
      memoryLimits: "2.5Gi"
      environment:
        IDAM_API_URL: https://idam-api.platform.hmcts.net
