apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plum-fastapi-backend
spec:
  chart:
    spec:
      chart: ./stable/plum-fastapi-backend
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: hmcts-charts
        namespace: flux-system
  values:
    global:
      enableKeyVaults: true
    python:
      ingressHost: plum-fastapi-backend-aat.service.core-compute-aat.internal
      image: hmctsprod.azurecr.io/plum/fastapi-backend:prod-5256c5e-20260821153359 # {"$imagepolicy": "flux-system:plum-fastapi-backend"}
      workloadClientID: ${WORKLOAD_IDENTITY_ID}
      keyVaults:
        plumsi:
          secrets:
            - name: appinsights-connection-string
        sps-ai-kv-stg:
          excludeEnvironmentSuffix: true
          secrets:
            - name: apim-subscription-cnp-plum-fastapi
      environment:
        RECIPES_SERVICE_URL: http://plum-recipe-backend-java
        APPLICATIONINSIGHTS_CONNECTION_STRING_FILE: /mnt/secrets/plumsi/appinsights-connection-string
        AI_GATEWAY_URL: https://ai-gateway.staging.platform.hmcts.net/ai/platform/foundry/models/v1/chat/completions
        AI_GATEWAY_SCOPE: api://97f4f377-1eda-417b-8367-17c2c64cecd8/.default
        AI_GATEWAY_MODEL: gpt-4o
        AI_GATEWAY_SUBSCRIPTION_KEY_FILE: /mnt/secrets/sps-ai-kv-stg/apim-subscription-cnp-plum-fastapi
