apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plum-fastapi-backend
spec:
  values:
    global:
      enableKeyVaults: true
    python:
      ingressHost: plum-fastapi-backend-sandbox.service.core-compute-sandbox.internal
      image: hmctssbox.azurecr.io/plum/fastapi-backend:latest # {"$imagepolicy": "flux-system:plum-fastapi-backend-sbox"}
      useWorkloadIdentity: true
      workloadClientID: ${WORKLOAD_IDENTITY_ID}
      keyVaults:
        plumsi:
          secrets:
            - name: appinsights-connection-string
            - name: ai-gateway-subscription-key
      environment:
        RECIPES_SERVICE_URL: http://plum-recipe-backend-java
        APPLICATIONINSIGHTS_CONNECTION_STRING_FILE: /mnt/secrets/plumsi/appinsights-connection-string
        AI_GATEWAY_URL: https://ai-gateway.sandbox.platform.hmcts.net/ai/platform/foundry/models/v1/chat/completions
        AI_GATEWAY_SCOPE: api://b3bfa0f5-faa5-4d10-bba0-e284144aea89/.default
        AI_GATEWAY_MODEL: gpt-5.5
        AI_GATEWAY_SUBSCRIPTION_KEY_FILE: /mnt/secrets/plumsi/ai-gateway-subscription-key
