apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${NAMESPACE}
  namespace: ${NAMESPACE}
  annotations:
    azure.workload.identity/client-id: "fb7b6d06-e658-4a4f-b514-aa0529ea2890" # azure-devops-aat-mi