apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: labs-debolina-seal
  annotations:
    hmcts.github.com/image-registry: hmctssandbox
spec:
  image: hmctssandbox.azurecr.io/labs/debolina-seal
