apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fact-cron-trigger-audit-cleanup
spec:
  releaseName: fact-cron-trigger-audit-cleanup
  values:
    job:
      schedule: "0 9 * * *"