apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: camunda-ui
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/camunda/bpm:pr-1078-836c53a-20260914173912 #{"$imagepolicy": "flux-system:demo-camunda"}
      ingressClass: traefik
