apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: camunda-ui
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/camunda/bpm:pr-1078-524c0ad-20260902130220 #{"$imagepolicy": "flux-system:demo-camunda"}
      ingressClass: traefik
