apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: camunda-ui
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/camunda/bpm:pr-1078-9a308d3-20260908141947 #{"$imagepolicy": "flux-system:demo-camunda"}
      ingressClass: traefik
