apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: et1
spec:
  releaseName: et1
  values:
    base:
      image: hmctsprod.azurecr.io/et-pet/et1:prod-b428c0d-20261001141657 #{"$imagepolicy": "flux-system:et-pet-et1"}
  chart:
    spec:
      chart: ./stable/et-pet-et1
      sourceRef:
        kind: GitRepository
        name: hmcts-charts
        namespace: flux-system
      interval: 1m
