apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: admin
spec:
  values:
    base:
      image: hmctsprod.azurecr.io/et-pet/admin:prod-5788a7c-20260731122143 #{"$imagepolicy": "flux-system:demo-et-pet-admin"}
