apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: admin
spec:
  values:
    base:
      image: hmctsprod.azurecr.io/et-pet/admin:prod-334b120-20260810111029 #{"$imagepolicy": "flux-system:demo-et-pet-admin"}
