apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: admin
spec:
  values:
    base:
      image: hmctsprod.azurecr.io/et-pet/admin:prod-5694b68-20260805114816 #{"$imagepolicy": "flux-system:demo-et-pet-admin"}
