apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: artifactory-oss
  namespace: artifactory
spec:
  timeout: 20m
  releaseName: artifactory-oss
  chart:
    spec:
      chart: artifactory-oss
      version: 107.133.12
      sourceRef:
        kind: HelmRepository
        name: artifactory
        namespace: artifactory
  interval: 1m
  values:
    artifactory:
      artifactory:
        admin:
          secret: admin-pw
          dataKey: bootstrap.creds
        consoleLog: true
        joinKeySecretName: join-key
        masterKeySecretName: master-key
        persistence:
          storageClassName: managed
          size: 128Gi
        database:
          allowNonPostgresql: true
        # Artifactory OSS 7.125+ appears to have a bug where it tries to connect to JFConnect microservice to verify entitlements/licensing
        # But this microservice does not exist within OSS and there is no licensing to check, this causes frontend microservice to never load
        # So explicitly disable JFConnect to prevent this issue
        # Bug for this has been raised: https://github.com/jfrog/charts/issues/2233
        systemYaml: |
          shared:
            database:
              allowNonPostgresql: true
          jfconnect:
            enabled: false
        configMapName: artifactory-oss-configmaps
      ingress:
        annotations:
          traefik.ingress.kubernetes.io/router.tls: "true"
        className: traefik
        enabled: true
      nginx:
        enabled: false
      postgresql:
        enabled: false
    postgresql:
      enabled: false
