apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bp-cron-trigger-daily-checks
spec:
  releaseName: bp-cron-trigger-daily-checks
  values:
    job:
      # mon-fri, 11:30am-4:30pm, on the half hour
      schedule: "30 11-16 * * 1-5"
