apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${NAMESPACE}
  namespace: ${NAMESPACE}
  annotations:
    azure.workload.identity/client-id: "acd51ca4-93e1-4154-b241-a3bfee563830"
automountServiceAccountToken: false
