apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ccd-api-gateway-web
spec:
  releaseName: ccd-api-gateway-web
  values:
    nodejs:
      environment:
        CORS_ORIGIN_WHITELIST: "https://www-ccd.aat.platform.hmcts.net,https://manage-case.aat.platform.hmcts.net"
        TIMING-ALLOW-ORIGIN: "https://www-ccd.aat.platform.hmcts.net"
        DUMMY_VAR_TO_REDEPLOY: 2
