apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ccd-api-gateway-web
spec:
  releaseName: ccd-api-gateway-web
  values:
    nodejs:
      image: hmctsprod.azurecr.io/ccd/api-gateway-web:prod-1c965fb-20260327101625 #{"$imagepolicy": "flux-system:demo-ccd-api-gateway-web"}
      environment:
        CORS_ORIGIN_WHITELIST: "*"
        TIMING-ALLOW-ORIGIN: "https://www-ccd.demo.platform.hmcts.net"
        DUMMY_VAR_TO_REDEPLOY: 1
