apiVersion: v1
data:
    token: eG94Yi01NDAzMDkxNDMyMS03NDU4OTQ2NjE0NjkwLUY2MjBmVjh2U3l3OFhXZ2xPWXZRTTRzcg==
kind: Secret
metadata:
    creationTimestamp: null
    name: slack-token
    namespace: ${NAMESPACE}
type: Opaque
