apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: civil-sdt-commissioning
  namespace: civil
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/civil/sdt-commissioning:prod-54f705f-20260715124820 #{"$imagepolicy": "flux-system:demo-civil-sdt-commissioning"}
