apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xbp-cron-trigger-daily-checks
spec:
  releaseName: xbp-cron-trigger-daily-checks
  values:
    job:
      schedule: "0 10-14 * * 1-5"
