apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: probate-business-service
  namespace: probate
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/probate/business-service:prod-dc31561-20260608140149 #{"$imagepolicy": "flux-system:demo-probate-business-service"}
      environment:
        # Does what it says on the tin - if this changes then demo should redeploy
        CHANGE_TO_REDEPLOY_DEMO: 20251215
        SERVICES_NOTIFY_INVITEDATA_INTESTACYLINK: https://probate.demo.platform.hmcts.net/executors/intestacy-invitation/
