apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: probate-business-service
  namespace: probate
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/probate/business-service:pr-1191-ebc6da6-20260520170737
      environment:
        # Does what it says on the tin - if this changes then perftest should redeploy
        CHANGE_TO_REDEPLOY_PERFTEST: 20251215
        SERVICES_NOTIFY_INVITEDATA_INTESTACYLINK: https://probate.perftest.platform.hmcts.net/executors/intestacy-invitation/
