apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: am-judicial-booking-service
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/am/judicial-booking-service:prod-58d59a8-20260528103046 #{"$imagepolicy": "flux-system:demo-am-judicial-booking-service"}
      environment:
        AM_INFO: true
