apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: et-cos
spec:
  releaseName: et-cos
  values:
    java:
      ## Temporarily forcing the image on AAT
      image: hmctsprod.azurecr.io/et/cos:prod-69344a2-20260311132738
      environment:
        DB_QUEUE_ENABLED: true
        CREATE_UPDATES_POLL_INTERVAL: 60000
        UPDATE_CASE_POLL_INTERVAL: 60000
