apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ia-case-payments-api
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/ia/case-payments-api:prod-c21bff0-20260312155600 #{"$imagepolicy": "flux-system:perftest-ia-case-payments-api"}
