apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ia-case-payments-api
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/ia/case-payments-api:prod-36e9a34-20260317133924 #{"$imagepolicy": "flux-system:perftest-ia-case-payments-api"}
