apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../../rbac/nonprod-role.yaml
namespace: snl
patches:
  - path: ../../snl-backend/aat.yaml
  - path: ../../snl-ui/aat.yaml
