apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fees-register-frontend
spec:
  releaseName: fees-register-frontend
  values:
    nodejs:
      image: hmctsprod.azurecr.io/fees-register/frontend:prod-ac42136-20260715104811 #{"$imagepolicy": "flux-system:demo-fees-register-frontend"}
      environment:
        DUMMY_RESTART_VAR: false
        IDAM_LOGIN_WEB_URL: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/o/authorize
