apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fact-data-api
spec:
  releaseName: fact-data-api
  values:
    java:
      image: hmctsprod.azurecr.io/fact/data-api:prod-eaba10d-20260326111829 #{"$imagepolicy": "flux-system:fact-data-api"}
  chart:
    spec:
      chart: ./stable/fact-data-api
      sourceRef:
        kind: GitRepository
        name: hmcts-charts
        namespace: flux-system
      interval: 1m
