apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ccd-case-print-service
spec:
  releaseName: ccd-case-print-service
  values:
    nodejs:
      image: hmctsprod.azurecr.io/ccd/case-print-service:prod-0cca41a-20260501182721 #{"$imagepolicy": "flux-system:ccd-case-print-service"}
      environment:
        DUMMY_VAR_TO_REDEPLOY: 1
