apiVersion: v1
data:
    apiToken: ENC[AES256_GCM,data:iyw61W/se9MoSlBMb4K54QMJIzins5sICT89gb3y0rPXpZRdqcVHeUGCwuMFuP2FE5CjzCHr0HFoekAWebk9OBf3c97owPmdrM1O0K2+CbStHxGlowQlvz2CuTeMHM8Zo4vQKS83tD/KI5XPBlZZugGKMxhCCCy+lOR81ophZOU=,iv:P8uFZEO8Ut0b6JaSOtQW81BCwnbUTsxQ6HeUnhlTBaM=,tag:pIZpxefqJG9Vlyb+dyXTRQ==,type:str]
    dataIngestToken: ENC[AES256_GCM,data:X5QlVzAEF9Txzd+scvHSA6ngejJoDepukp+C6jWwsfxMkCku5PYI/R0yqTw3QTzhlbx+WuSlzJfbu4aUZfg8PHV5Ulqhswu1YiXH6wXW1PFLKZ+kzXRS0SD2/Ydp4TKA6bAswlXeXRs4iQcmoyCKFwpdC9aVeTUFHOisIbakaq4=,iv:HlBd2ao6cKAULBBVCa6olsUM8PZ3/qRNMGgIZG4HaS4=,tag:aROnGgo2Da5WgHJUHmDrWA==,type:str]
kind: Secret
metadata:
    name: dynakube
    namespace: dynatrace
type: Opaque
sops:
    azure_kv:
        - created_at: "2023-02-20T14:44:30Z"
          enc: efneA5zaMDHpwKgXRgVr1yiZM9HL-TvhE7yxqYejCGCReFLRoqFbozrm3MkY1LkwoH8JqRw7e13HGb1YLLi1g9GCot8mVvNlLKQnw5O4p2ZwReIDn6MHZ2QSnycQwkDPwjAr-dj2UgAKr5FzE9pH78852tUak3dw9NY28qqMI58ftBsdU1eLU_5wiRb7mfnn18nHUzzh5xsoPBYer5V25zYo0y-YqYqigRoGAmalqK3QtyyWXR9ZpKxVI6Tin7YhUVQ0qCfzs5Pg5xKv1hOWVfVbe9a4sBJTfHtguvZcDtHAxR1R6dEOsVDsySgowtc_dhWtuVGpz3GbgAra3iC3tw
          name: sops-key
          vault_url: https://dcdcftappsprodkv.vault.azure.net
          version: 44f7be9dc801456688ba4ddea9d552e8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T14:28:20Z"
    mac: ENC[AES256_GCM,data:izlkwz0TFk9XqgtDvC9n4EqZLNDM3h5J1kFGcmgx7KAb+tru2WgL5l0Y/CGiZ1lmJ6pzPmVAukoHCy2UUVVymo/k7ptapk9vLbZP9YQsYVNKpkoKGGDJB5rchiuiEzuxeK8JT+7nON79nC5BNX3l+11/hAnOnjYp0W+gb1MyOdQ=,iv:R5RIBpccYTbrF6+lSmD8cWYfqF3uHZBQ9GpmalRMx6M=,tag:/r03/4lv1LEz4ZGIIvFjmg==,type:str]
    version: 3.13.3
