apiVersion: v1
data:
    apiToken: ENC[AES256_GCM,data:DRfu2cCzo/c1KpF/ajck4apferpq19bWcv+orUfv4DxThJiSAn/JeS8ufpJDnvbTlj+yF+uJG+oyfyIW9qTCSBUCRrTlA/L+1Lq7SdsNQsQMghxAFpADnBK9ROIWVUWs5cEQbiuVP2Dfs/R6E53vhNEDGz6ocWzrH2nYStdCBU4=,iv:9swXoqWRXzyAMTNV+7Y3AABWrB+vxpz69+ZFmSHW4mM=,tag:ZKouzfsBLB0dC1s+nRTNYA==,type:str]
    dataIngestToken: ENC[AES256_GCM,data:6MmH18RhNKpuXAns6n1nTaYWbCZlJIfLIKhARQlPPgO7cwuHd52hfdhT1tDVLXBXcWrCIJpXgDEcH9WEH8mkUQM/wgjP3kU5ss3srnetndvutetZ3XQUzE1zNXSSaqY9aKwTDD4pTILFe2JhezcuPGkjvwQJpmDwha/RNALnttk=,iv:l6EoQSIQRP2AQ5nWb/aarzqjLSOX2eKrdsX0mqH6Cgc=,tag:Jymbeqv/emII0hyNFYJsyQ==,type:str]
kind: Secret
metadata:
    name: dynakube
    namespace: dynatrace
type: Opaque
sops:
    azure_kv:
        - created_at: "2023-02-20T14:44:30Z"
          enc: efneA5zaMDHpwKgXRgVr1yiZM9HL-TvhE7yxqYejCGCReFLRoqFbozrm3MkY1LkwoH8JqRw7e13HGb1YLLi1g9GCot8mVvNlLKQnw5O4p2ZwReIDn6MHZ2QSnycQwkDPwjAr-dj2UgAKr5FzE9pH78852tUak3dw9NY28qqMI58ftBsdU1eLU_5wiRb7mfnn18nHUzzh5xsoPBYer5V25zYo0y-YqYqigRoGAmalqK3QtyyWXR9ZpKxVI6Tin7YhUVQ0qCfzs5Pg5xKv1hOWVfVbe9a4sBJTfHtguvZcDtHAxR1R6dEOsVDsySgowtc_dhWtuVGpz3GbgAra3iC3tw
          name: sops-key
          vault_url: https://dcdcftappsprodkv.vault.azure.net
          version: 44f7be9dc801456688ba4ddea9d552e8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T16:08:28Z"
    mac: ENC[AES256_GCM,data:RVxHh5oG6us7HnXLlqEmK1SYcO4n+ZJcGDnSdUaDBZvtapZP/FAkrSrmHVro878jQ4iX9SOf+a1So+sDfp60bZxhM6WpgdScYz+21UINZ6e7S2hh4/iggyvJdvLmffN/M2agkd1QO0RhMZTj8kipdHtfphdcQZYxWYiqAfonSRY=,iv:P46l9iZDdokWJrvr0k/ApXIN/lkz4X4reGY+CXr/h/k=,tag:hcODcwfHXRVTyKCP/VPASA==,type:str]
    version: 3.13.3
