apiVersion: v1
data:
    apiToken: ENC[AES256_GCM,data:PMiTth3Ueqyc6J3Ldg61FV6jPua7q1OfJG9mM4yHRyiXl3nHqZAQOl83vZWimeyQP8S4Eh9CSETsORmQzr9jPHGVF8rtiBMJlFNfMXuAM4sGx7jue3Xn0e68QFcvcZ5SAu2K8wuq8RZdUO+bb3GvUFdTV0oXfWRMuUhxw0bQxvLPgp2Z,iv:mm07/qHKDeOoWUX2m6/JFuIVFS065tb4aHe52fcdJVQ=,tag:t7a1KHuEafO4Q3k7q1poZQ==,type:str]
    dataIngestToken: ENC[AES256_GCM,data:9YW5BaKz7tHkgFuJ/Wz5EeoX9zBtRaDozKEmayKOfMUlI0nMtVNxWP2t6Es2gOBBjLeMNIYUHddCPRzIKzHnSy5tn0IOA1Z8uF9xjJhQzix4wgV4FgvxmRghxTyIifXFJl5zfGbD4J2gDfM133KNCwkj9AH0cqJ0bJ5fmg3TTjzHi65r,iv:4hsZRasFT6YrZ9nmVWq/Bcippwt9K7F8x+1RrcK2Lfc=,tag:PEpLjIzq2EFD2zs3uqAUBg==,type:str]
kind: Secret
metadata:
    name: dynakube
    namespace: dynatrace
type: Opaque
sops:
    azure_kv:
        - created_at: "2023-02-20T14:44:30Z"
          enc: efneA5zaMDHpwKgXRgVr1yiZM9HL-TvhE7yxqYejCGCReFLRoqFbozrm3MkY1LkwoH8JqRw7e13HGb1YLLi1g9GCot8mVvNlLKQnw5O4p2ZwReIDn6MHZ2QSnycQwkDPwjAr-dj2UgAKr5FzE9pH78852tUak3dw9NY28qqMI58ftBsdU1eLU_5wiRb7mfnn18nHUzzh5xsoPBYer5V25zYo0y-YqYqigRoGAmalqK3QtyyWXR9ZpKxVI6Tin7YhUVQ0qCfzs5Pg5xKv1hOWVfVbe9a4sBJTfHtguvZcDtHAxR1R6dEOsVDsySgowtc_dhWtuVGpz3GbgAra3iC3tw
          name: sops-key
          vault_url: https://dcdcftappsprodkv.vault.azure.net
          version: 44f7be9dc801456688ba4ddea9d552e8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T12:43:57Z"
    mac: ENC[AES256_GCM,data:yopHlOH+mbeMYBTYP0QtbwaK8f2QOZpXD96SLwssfAKokibyR6mSU1DGcUiURGKhOamaTXDcbpOYjvxNWKIuk/4+UZWnW+ruUnkYJtZ6OJj7CAXSUiOhEZi86f9deQDf33ecYptHbsjW8HXtcTzUfiHeg8bJvXEdDggxunKMFeA=,iv:705qOWxUqAqPjsmYwkgNK4r/AtqCnrLiOXRjsHVq6ew=,tag:POQzh2JDAhUyXD6UJ9qtSw==,type:str]
    version: 3.13.3
