apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rota-optimiser
spec:
  releaseName: rota-optimiser
  values:
    java:
      image: hmctsprod.azurecr.io/rota/optimiser:prod-9cce1f8-20260924084853 # {"$imagepolicy": "flux-system:rota-optimiser"}
  chart:
    spec:
      chart: ./stable/rota-optimiser
      sourceRef:
        kind: GitRepository
        name: hmcts-charts
        namespace: flux-system
      interval: 1m
