apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cmc-demo
  namespace: money-claims
spec:
  releaseName: cmc-demo
  timeout: 900
  forceUpgrade: true
  chart:
    spec:
      chart: ./stable/cmc
      sourceRef:
        kind: GitRepository
        name: hmcts-charts
        namespace: flux-system
      interval: 1m
  values:
    ### CMC SERVICES ####
    cmc-claim-store:
      java:
        releaseNameOverride: "cmc-demo-claim-store"
        image: hmctsprod.azurecr.io/cmc/claim-store:prod-64db173-20260309124034 #{"$imagepolicy": "flux-system:cmc-claim-store"}
    cmc-citizen-frontend:
      nodejs:
        releaseNameOverride: "cmc-demo-cmc-citizen-frontend"
        image: hmctsprod.azurecr.io/cmc/citizen-frontend:prod-fc1a866-20260304105354 #{"$imagepolicy": "flux-system:cmc-citizen-frontend"}
