apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hmc-hmi-inbound-adapter
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/hmc/hmi-inbound-adapter:pr-274-8a4fb62-20260527091545 #{"$imagepolicy": "flux-system:demo-hmc-hmi-inbound-adapter"}
      environment:
        LOGGING.LEVEL.UK.GOV.HMCTS.REFORM.HMC.CONFIG: DEBUG
        LOGGING.LEVEL.UK.GOV.HMCTS.REFORM.HMC.SERVICE: DEBUG
        HMC_SERVICE_BUS_QUEUE: hmc-from-hmi-demo-temp
        IDAM_OIDC_URL: https://idam-web-public.demo.platform.hmcts.net
        OIDC_ISSUER_FORGEROCK: https://forgerock-am.service.core-compute-idam-demo.internal:8443/openam/oauth2/realms/root/realms/hmcts
