apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: actions-runner-controller
  namespace: github-arc
spec:
  type: oci
  url: oci://ghcr.io/actions/actions-runner-controller-charts
  interval: 30m
