apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fact-admin
spec:
  values:
    nodejs:
      image: hmctsprod.azurecr.io/fact/admin:pr-938
      imagePullPolicy: Always
      environment:
        HMCTS_ACCESS_URL: 'https://hmcts-access.{{ .Values.global.environment }}.platform.hmcts.net'
