apiVersion: v1
data:
    apiToken: ENC[AES256_GCM,data:keDlWThKeSBNRUC+tHpQ/YlOCETcmQHWO/jDlbfs9XzhqrOzemFqG2JjcqkUul/nmKZZaeviOBLGIjmBOps09wnB/jYk4buCtcEyDgmJ+c3EV/JBAa+YQ/jkrxkHxPggXa7nwO7Hnl6/so8iaWEC3J15eoUJfaRNUBVO+C6Jp5E=,iv:glZewnXY1dFj6/+zk0SUDk5Krqh1bH4wMntFY1h1GYc=,tag:k4PDfDjzR8xoU5u0SxCkLQ==,type:str]
    dataIngestToken: ENC[AES256_GCM,data:QU3U9DCnmJtkZW3RWCEjDk61Ca7MUZTaVpztRSRwGsis6jdBydWoCJ8zsVl4Ms5wvDRVq4qu543OE4QPfe99LeAoTuph3f53g9EAAQiYPfcpt3nK5ECJrXdKv+37qh+belvGa7qv61qJEseVcKLnbQ+aletLbBKvhxjNJOzRtkU=,iv:vqVBdg7iQxlBJe7yjYS7d5vi1OaD6PCi2mFgRepjzBI=,tag:4L0M40yyTV31l0WaXp1gCA==,type:str]
kind: Secret
metadata:
    name: dynakube
    namespace: dynatrace
type: Opaque
sops:
    azure_kv:
        - vault_url: https://dcdcftappsdemokv.vault.azure.net
          name: sops-key
          version: 7a5cc0c79b02466c86bc594c431e00f7
          created_at: "2026-03-10T10:59:11Z"
          enc: X0d8FKsuSM0AHFVGKGD8IJFYfJkD3FntyV1RHMP0_xnUFXgW8zXI8ETXxpAIERXcBL8SbG_g8RJ3JQG6UfX9cJRWZKb1hCpTHxMeINmm6taquQBVM6hvpgIFVCIufOazcCJprIESwP5jSh1KsMK435AnAzgcWg95KsiqcHacOx4m-Wu8nPGjLd7g7g4vLQYOPy2r-cyt645zKTUBl0BWSSrAwXv04Xr9M00L3-4YIRmjvlJnOsCMwHeNjvQw8j4Ud-QTckD3svVhhidQIyqg2OrsYnjLSaWRh74U7uEWAyUzp5VBIrgNdQ8I9oU7XkHCbrFdTyUeZFq7PjqIDpRDfA
    lastmodified: "2026-03-10T10:59:12Z"
    mac: ENC[AES256_GCM,data:vBcMh8rL2nAwRRS+3WmALoi+vnQNVazuq6cAEdFVGaRjBjkJX0TzkQ2uNGKzudjSZuccCGeon6KfgjAGiqB7jJZIrFIAqE68L8z+KEo5yVkGpQWiSJZBADTBPId6+etdENjFAXaLrafsnIOG8XgkkcyC2qRXUqEG/q6CtWgDftw=,iv:NdbgmQZi9J/mvSFZM/+HAKUvWD+DgS3rtp0/ZszjKOw=,tag:Z0iT/nHa/r+10EzzVJsRCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
