apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../snl-backend/image-repo.yaml
  - ../snl-backend/image-policy.yaml
  - ../snl-ui/image-repo.yaml
  - ../snl-ui/image-policy.yaml