apiVersion: v1
data:
    DOCMOSIS_ACCESSKEY: ENC[AES256_GCM,data:652ltbh6iuFx7uDyyCoeog==,iv:RXW/p8pXpjFQ2/FWO+o8Luz8fUTNFFWUfWAJmrQKsfU=,tag:ycFT3JON7Y4l4pEXaLddBQ==,type:str]
    DOCMOSIS_ADMINPW: ENC[AES256_GCM,data:JM6QCdd1GuREaj0YsJ6uggJFa1s=,iv:lS0GcwFjG2SGfpMjzKK/LMlIln2ENxCRMvk1XBjLFjs=,tag:Ipm+fceFpJDRp+vFyx6RvA==,type:str]
    DOCMOSIS_KEY: ENC[AES256_GCM,data:H0QnH+Teupw4rH+WpUoo5S3RPk26J1XQwgxjMBKCb4yam5XSFALNRJvPrE/IJiFiMjP9GsuNJrCbKgUl1fFM/vBcK2d7dTvf,iv:BSj0wZA1oC1JWA/jRgYKwSZUxo/9B2P1Sr+7eXGIxTM=,tag:XxvqDjtNypJ3R62CFlXfvg==,type:str]
    DOCMOSIS_SITE: ENC[AES256_GCM,data:A8JmTq+Xbqo60hfCpa5Yrn6CR9WbYzj5GsPERt2t/s8+3Z31QsNM8TNA5NT5K/d1Bc3FgUw2fG8HagtGV23jR6ciPJEeOyoQymNqDPQ5JWgTuDFMom6B4z57hAcecX93QJrZ/lEcV22h9qBGfh1PUri4jacqfz89hox0lQ==,iv:j3Bvy70FwaGWT/I9QMrknf8HuHwsm67QuzlPlaRePig=,tag:JfHYmbKjPDiZDC/JN5Ojcg==,type:str]
    DOCMOSIS_TEMPLATESDIR: ENC[AES256_GCM,data:v1+q21f+zuiwMe9GWrQerkwwoJwi16Kj3/ZE5h9ILF06cwrPAx3pLGD5zCkFUS0lAlMV0zOTg8PWSnWkbvo+e/3bDcyLMLNJ+lFYO3xorctGNc3vi1zEiLPnRogy33PSuAkThavy7BCjp4gElT2ecpyzEvwxrzbW05GhaUX6xfmoz1fk4japGCYln0zn9FnNK6tUYmZu9EfBdDbsQVdeQId+T0foO/sMNhMQsA==,iv:Z/C4D8TaD1VSOVtUEdTRTp1pL7VXFII9PO16Sz+yN9M=,tag:5DkiqtR+hrHmmOnufjgJUQ==,type:str]
kind: Secret
metadata:
    name: docmosis-secret
    namespace: docmosis
type: Opaque
sops:
    azure_kv:
        - created_at: "2026-09-28T13:58:06Z"
          enc: DbaBgtXL6YhtjMvvreP1hO2aCr-PJgPQUOyAHQzqRm-5uUCXXtZckE8EldcfZjOdROMpWQEo2WwGvRan62JeiJAncY5RyWZEGrTGNToE1t0BjC5Dl0Sz6mw880Vx6_6AhVnmqnZTA3caCc7vRV_3HbCZ1huMy75wspxhMLMPQDhfPx83w4qajMTgRCvzigyvpdkHHAN7Ec1dR_qI2AnKrUMAT7yiohdHfIqxD2QlOrQLt7AnwxfXYiJN4FQdGRDAs-TkOSuegYmdeeY-ILTk-cKLQoKsdAo7kvQc94I9-IFlZFfAKWJa5plnWCM1vdUtSt19aIxNTqOO2waVAPW-vA
          name: sops-key
          vault_url: https://dcdcftappssboxkv.vault.azure.net
          version: 4dfa9dd4b0444f03bd64e2128e347537
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T13:58:09Z"
    mac: ENC[AES256_GCM,data:uE0r88D7RZQIurmPSV9E/s2RuZ2oDfv2BNg5mUvNkDgf1jSuOBc3SAtJ+2G1HWfYz6hVuQfkP/7rAe888AFfa5/N0rQ8+nnLnsFZZxfJ8knpG29GUjfmTjHB1STqdgU2FGLKSslTT8rXAHBuJVGYeNAGe5uj7F+msGljY5eLi98=,iv:X679XkfXWdAc/BPQqQpNwzUSqP4m1nc9sjt+Ah5MDCE=,tag:/v8nI5smNDED3wDc0a0znw==,type:str]
    version: 3.13.3
