apiVersion: v1
data:
    DOCMOSIS_ACCESSKEY: ENC[AES256_GCM,data:2P6pCJFiVzFJooK5MXGL9A==,iv:aM9JEBPHdXtuPR3G9BFN+jsoBxcX63FCDbXwHOuMmbM=,tag:LYo7xQEKzmPwnwvgadx1JQ==,type:str]
    DOCMOSIS_ADMINPW: ENC[AES256_GCM,data:UTTNmyKRc+QzxDaJq4w8L8a2ww4=,iv:WNCkWzQfqO97EKOccHwiUUcZvWjC/fP4Tq2x8Vj756I=,tag:IDHRiatzvFKNBaq2RvvmqQ==,type:str]
    DOCMOSIS_KEY: ENC[AES256_GCM,data:72obKIqChsv8rjLqmfJncAI3BBxpD6zuKqXFFl5C4TW/hLWFlnatU4jcmuiWRi+U7QkH8rcVnp62ak6a0qfKZquI7zE64g+/,iv:KtyfMsMVbnisfjUJKwO49QcCvyq9rFy7liDECTiYoIg=,tag:awFgxwqcYTger40c6HV/Ww==,type:str]
    DOCMOSIS_SITE: ENC[AES256_GCM,data:4PZ5dAG7orbCDhYTsJaXFYoIA8zX5oVA4wUSd2kETP/5x8t0y3xDPsUTqgJJJmDYQ5l6dQxMjRomc2zuXM4gqI2BmI2wBZTjWecXpA5pMniD6AUG+2LfZm56mINreEmNbjx4/VS6EzaqSpDHombGIop6/LcXKJSvNTB34A==,iv:MK36jrj8OK/sayZuJQsFzcEp/kybkxH/dJX9Ewmh7ZQ=,tag:znFFHF3oEVnNLMwq9Gj8lg==,type:str]
    DOCMOSIS_TEMPLATESDIR: ENC[AES256_GCM,data:qGiNhzJ+u/x1G16N1Pe2kQ9O10abW/QoMUfzw2NDL6aB8VkJ+6ia2K6zN65ug2DlWupWPmGSZig=,iv:5IhDMeFcrBK/XAnNKZV39advrf8s/t19fpdsoUm8aRg=,tag:J0FNEaUwIp+tzlX0jrRlKw==,type:str]
kind: Secret
metadata:
    name: docmosis-secret
    namespace: docmosis
type: Opaque
sops:
    azure_kv:
        - created_at: "2026-09-28T14:43:38Z"
          enc: seWOfFPmpj5H8ERJ0nGVScTACvhA41KSJjE-WbrU1U713_4odjUjPMe9QqMRd6tAWiokzhLgt0ihw8Ns0fsj5W90u-vNIvNLBeRc4b9v-mvgPTQxVYwja8RuNNVLj1IByT5mGsRYGhE8tQA2rTHYb3KQ3NtwwsIViIIckFVc0IQv3_x8ghr7xkD9Bd0_kaZ6_yh5CVmDoWQK5HjXRrgmKN9XEVXmF9tXLOW6tkhNf2zuBFAnnvRM81s8FW4EwuIQ_wC_PsdQjpYG9v0_YEk_huFx2CwOzyT8xVsYfy9uR4FHlbxLfFgsTm5uL05MxQE09WIz1CUTYcv9Qa7-relXvw
          name: sops-key
          vault_url: https://dcdcftappssboxkv.vault.azure.net
          version: 4dfa9dd4b0444f03bd64e2128e347537
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T14:43:39Z"
    mac: ENC[AES256_GCM,data:Vc1s5EB5+ShsWSrXpZLn5QfAsuydKPmEzUxYydV/dPZ9H/5xJ9FkOZoHqDpCxipSSpmP3lee/bk0f7XJ8nfEKcqI9Ztp3PnsRy28YGrnGa+XMBLSqiAe+g4Clv8K0vVpnuHBeLuFaTOl17fsyfJo866FEyOk3k9a4l6X++VQ+EY=,iv:C0uhMCkJ7Ju1NQ3Lo9bzk9II9jwSxaQTeoVkM0JAvbw=,tag:ibcrT9NPgvzNAm5b5c/rAA==,type:str]
    version: 3.13.3
