apiVersion: v1
data:
    DOCMOSIS_ACCESSKEY: ENC[AES256_GCM,data:8Wc806IbKIdCTT/KdsuRBw==,iv:QUVi/9Ps/QGVLbCTMRW82d1gTse2mtRWYXf5tCZ7Px0=,tag:MEzZNTSVb4l+MCdS0lJxQA==,type:str]
    DOCMOSIS_ADMINPW: ENC[AES256_GCM,data:z9lL8on9pdkYVGyorHS+zCkGStg=,iv:fprwyqdc6yzN5LZPpP/fjaBmvg7irt8xfMklhk/q4wA=,tag:1FbhZe5tlFGAF79+Gc3ZiA==,type:str]
    DOCMOSIS_KEY: ENC[AES256_GCM,data:OPd/qE+yAhqR43MzDsfZuG9/wPAd02zjv4n+aZEZwHefxQMLWOaO67g2U22BFIlRyIo5oCI+Iqc/CTT2aqEJjwEBFSVIz68P,iv:atrvc8a3O9L4wCZO9j/sE6ps3/egn/cEnTFZhAOsSxE=,tag:hhT4Gp86YsMmtHDYhxoKUg==,type:str]
    DOCMOSIS_SITE: ENC[AES256_GCM,data:XIwAraVKkNq/denWhEQ6zjqqs2ejQsIQ6lxhli6TCtvTSpMxhsb2GmkaL8k5eiby/lcJQUQNTXyVRDsHGBca+MVvAbSFAElUM2g6DpdWp9DDrRuR69Dca2vxQL0cmK6EqemEmFDroTFpxyRT343D0/9FS/jAT0MRc0gzvg==,iv:tajg4lZCfpqKHLtU4jPYiLLWCBJlL169NqVlF3OiWfY=,tag:qhhgNELHcsiCPeDgd80x7A==,type:str]
    DOCMOSIS_TEMPLATESDIR: ENC[AES256_GCM,data:vyd6u6r4nO41C5uVbpFuwKdYVE2GYmoO4P51L4hm4304B+Y3Bmgq1z8L7VqZxjlwet42kaTmqT8=,iv:Wx4oYDoyjMxRMmHbjRjn52NOsBrVotWTZuzKhhA7Ryk=,tag:2uO8ZuvnL5wRtg/tKGwSuA==,type:str]
kind: Secret
metadata:
    name: docmosis-secret
    namespace: docmosis
type: Opaque
sops:
    azure_kv:
        - created_at: "2026-09-29T14:06:24Z"
          enc: uz7t53rmT-jrU-_q5eWUm59dZN-Ye-o_UWBlN-11bxjSKbkMJpnubrOzznPvoZE0UBiEw4_cc-U8tqLSOkiSUjV84tAeSsTbF23ypinWm5rzw44HA3n8YkKZHhRpiZ4Dd8roL9Dz0FbnWtXFTa97bHcC-FBVuhdsTuxCWrdrM5h9uXsgPssAAs3rL3ITSxWfGELGr9UuZZ1c9oWRYfAn2Kd04q-rYuppRpH2ijIDwuh9X5DEfZkWQ2Bb4juvmx6MhMOxPrOyrhKAlSuLHAlFeYOUHzL1biuGCD0Lpjn1gsy0uWPfxgER9u1CPMYKbScEAFfXDmseXgjIOEZm84yRjw
          name: sops-key
          vault_url: https://dcdcftappssboxkv.vault.azure.net
          version: 4dfa9dd4b0444f03bd64e2128e347537
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T14:06:25Z"
    mac: ENC[AES256_GCM,data:znmr0mcdFuxgZJr//1UCWbUkET2FHSfDFhPuDHb2JhEFKLRmq5qm3zWFiu1vNAgwc5CJx1QCDFyXCeI0F3R4d43egf2z1DNRTA8ZzlzyBf5/wDtdgN/GOwkZa5EB46R9Om/3N8HXarg+w6MFbcmmHkvp0QLNFpXwXnWaRmlZCps=,iv:cQ9faqtZ57cVqiriFuA6cEmojZS3lE0ySwKvroJUR8s=,tag:7E5fQ8ymhiFsiNP/SU/u4g==,type:str]
    version: 3.13.3
