apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appreg-assessment-reader
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - nodes
      - pods
      - services
      - endpoints
      - serviceaccounts
      - configmaps
      - persistentvolumes
      - persistentvolumeclaims
    verbs: ["get", "list", "watch"]

  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - statefulsets
      - replicasets
    verbs: ["get", "list", "watch"]

  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs: ["get", "list", "watch"]

  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
      - validatingadmissionpolicies
      - validatingadmissionpolicybindings
    verbs: ["get", "list", "watch"]

  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
      - ingresses
      - ingressclasses
    verbs: ["get", "list", "watch"]

  - apiGroups: ["discovery.k8s.io"]
    resources:
      - endpointslices
    verbs: ["get", "list", "watch"]

  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
      - csidrivers
      - csinodes
      - volumeattachments
    verbs: ["get", "list", "watch"]

  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch"]

  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs: ["get", "list", "watch"]

  - apiGroups: ["scheduling.k8s.io"]
    resources:
      - priorityclasses
    verbs: ["get", "list", "watch"]

  - apiGroups: ["node.k8s.io"]
    resources:
      - runtimeclasses
    verbs: ["get", "list", "watch"]

  - apiGroups: ["cilium.io"]
    resources:
      - ciliumnetworkpolicies
      - ciliumclusterwidenetworkpolicies
    verbs: ["get", "list", "watch"]

  - apiGroups: ["kubescape.io"]
    resources:
      - securityexceptions
    verbs: ["get", "list", "watch"]

  - apiGroups: ["hostdata.kubescape.cloud"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: appreg-assessment-reader-amine
subjects:
  - kind: User
    name: Amine.Messaoui@HMCTS.NET
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: appreg-assessment-reader
  apiGroup: rbac.authorization.k8s.io
