apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dg-docassembly
  namespace: dg
spec:
  releaseName: dg-docassembly
  values:
    java:
      image: hmctsprod.azurecr.io/dg/docassembly:prod-7dea7ae-20260330071849 #{"$imagepolicy": "flux-system:demo-dg-docassembly"}
      environment:
        VAR_FV2: value2
