apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: idam-api
  namespace: idam
spec:
  releaseName: idam-api
  values:
    java:
      image: hmctsprod.azurecr.io/idam/api:prod-be57a62-20260805110808 # {"$imagepolicy": "flux-system:idam-api"}
