apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: idam-api
  namespace: idam
spec:
  releaseName: idam-api
  values:
    java:
      image: hmctsprod.azurecr.io/idam/api:prod-e29eb2c-20260914103555 # {"$imagepolicy": "flux-system:idam-api"}
      environment:
        LOGGING_LEVEL_LOGAUDIT: INFO
