apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: idam-api
  namespace: idam
spec:
  releaseName: idam-api
  values:
    java:
      image: hmctsprod.azurecr.io/idam/api:prod-7eef1ac-20260820140247 # {"$imagepolicy": "flux-system:idam-api"}
