apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  values:
    prometheus:
      ingress:
        ingressClassName: traefik
        hosts:
          - prometheus-00.demo.platform.hmcts.net
      prometheusSpec:
        retention: 30d
        # Scrape AKS managed Node Problem Detector metrics exposed on each node at port 20257.
        # https://learn.microsoft.com/en-us/azure/aks/node-problem-detector#metrics
        additionalScrapeConfigs:
          - job_name: aks-node-problem-detector
            scheme: http
            metrics_path: /metrics
            kubernetes_sd_configs:
              - role: node
            relabel_configs:
              - source_labels: [__meta_kubernetes_node_label_kubernetes_io_os]
                regex: linux
                action: keep
              - source_labels: [__meta_kubernetes_node_address_InternalIP]
                regex: (.+)
                target_label: __address__
                replacement: $1:20257
              - source_labels: [__meta_kubernetes_node_name]
                target_label: instance
    alertmanager:
      ingress:
        ingressClassName: traefik
        hosts:
          - alertmanager-00.demo.platform.hmcts.net
      config:
        receivers:
          - name: "slack_alerting"
            slack_configs:
              - channel: prometheus-alerting-nonprod-cft
                title: 'Demo-00 - {{ template "slack.default.title" . }}'
                text: "{{ range .Alerts }}{{ .Annotations.message }}\n{{ end }}"
          - name: "slack_critical"
            slack_configs:
              - channel: prometheus-critical-nonprod-cft
                title: 'Demo-00 - {{ template "slack.default.title" . }}'
                text: "{{ range .Alerts }}{{ .Annotations.message }}\n{{ end }}"
          - name: "null"
  valuesFrom:
    - kind: Secret
      name: prometheus-extra-values
