apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fact-admin-frontend
spec:
  values:
    nodejs:
      image: hmctsprod.azurecr.io/fact/admin-frontend:pr-136-6005d49-20260617074809
