apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fact-admin-frontend
spec:
  values:
    nodejs:
      image: hmctsprod.azurecr.io/fact/admin-frontend:pr-198-960b4c5-20260707082045
