apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fact-admin-frontend
spec:
  values:
    nodejs:
      image: 'hmctsprod.azurecr.io/fact/admin-frontend:pr-126'
      keyVaults:
        fact-kv:
          secrets:
            - name: session-secret
              alias: SESSION_SECRET
            - name: REDIS-V6-HOST
              alias: REDIS_HOST
            - name: REDIS-V6-PASSWORD
              alias: REDIS_PASSWORD
            - name: REDIS-V6-PORT
              alias: REDIS_PORT
            - name: bstrap-sso-client-id
              alias: SSO_APP_REG_ID
            - name: bstrap-sso-client-secret
              alias: SSO_APP_REG_SECRET
            - name: bstrap-sso-tenant-id
              alias: SSO_APP_REG_TENANT_ID
            - name: app-insights-connection-string
              alias: APP_INSIGHTS_CONNECTION_STRING
            - name: admin-frontend-app-reg-id
              alias: FRONTEND_APP_REG_ID
            - name: bstrap-admin-frontend-client-secret
              alias: FRONTEND_APP_REG_SECRET
            - name: api-app-reg-id
              alias: API_APP_REG_ID
  environment:
    FRONTEND_URL: 'https://fact-admin-frontend.demo.platform.hmcts.net'
