apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fact-admin-frontend
spec:
  values:
    nodejs:
      ingressHost: admin-new.find-court-tribunal.service.gov.uk
      environment:
        DATA_API_URL: https://fact-data-api.platform.hmcts.net
        PUBLIC_FRONTEND_URL: https://new.find-court-tribunal.service.gov.uk
        FRONTEND_URL: https://admin-new.find-court-tribunal.service.gov.uk
        DEPLOY: 1
