apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cath-postgres
spec:
  releaseName: cath-postgres
  values:
    nodejs:
      image: hmctsprod.azurecr.io/cath/cath-postgres:prod-d0b8064-20260921082131 # {"$imagepolicy": "flux-system:demo-cath-postgres"}
