---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: labs-harveymoj
  namespace: labs
spec:
  releaseName: labs-harveymoj
  chart:
    spec:
      chart: ./stable/labs-harveymoj
      sourceRef:
        kind: GitRepository
        name: hmcts-charts
        namespace: flux-system
      interval: 1m
  values:
    java:
      image: hmctssandbox.azurecr.io/labs/harveymoj:prod-[a-f0-9]+-(?P<ts>[0-9]+) # {"$imagepolicy": "flux-system:labs-harveymoj"}
      disableTraefikTls: true