apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: et-reconfiguration-cron
spec:
  releaseName: et-reconfiguration-cron
  values:
    job:
      image: hmctsprod.azurecr.io/et/cos:prod-40f5a6d-20260518104230 #{"$imagepolicy": "flux-system:et-reconfiguration-cron"}
      suspend: false
      environment:
        CRON_CASE_TYPE_ID: ET_EnglandWales
      schedule: "0 11 * * *"
    global:
      jobKind: CronJob
      enableKeyVaults: true
      environment: demo
