apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: jenkins-webhook-relay-fix
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/hmcts/jenkins-webhook-relay
  ref:
    branch: fix-use-newer-chart-function
  provider: github
  secretRef:
    name: github-app-credentials
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
