apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bulk-scan-payment-processor
spec:
  values:
    java:
      autoscaling:
        enabled: false
      replicas: 2
      image: hmctsprod.azurecr.io/bulk-scan/payment-processor:prod-7b92abb-20260526101431 #{"$imagepolicy": "flux-system:perftest-bulk-scan-payment-processor"}
      environment:
        REFRESH_PODS: "true"
