apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: amp-try-slc
  annotations:
    hmcts.github.com/image-registry: hmctsprod
spec:
  image: hmctsprod.azurecr.io/amp/try-slc
