apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: civil-rtl-export
  namespace: civil
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/civil/rtl-export:prod-0ad879e-20260312120107 #{"$imagepolicy": "flux-system:demo-civil-rtl-export"}
