apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: civil-rtl-export
  namespace: civil
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/civil/rtl-export:prod-70a22c3-20260813091306 #{"$imagepolicy": "flux-system:demo-civil-rtl-export"}
