apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wa-task-batch-maintenance
spec:
  values:
    job:
      image: hmctsprod.azurecr.io/wa/task-batch-service:pr-905-144427e-20260528103049 #{"$imagepolicy": "flux-system:demo-wa-task-batch-maintenance"}
      schedule: "30 15 * * *"
      environment:
        JOB_NAME: DATABASE_MAINTENANCE
        REFRESH_FLAG: "1"
    global:
      environment: demo
      tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
      jobKind: CronJob
