apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wa-task-batch-maintenance
spec:
  values:
    job:
      schedule: "30 0 30 2 *" # At 00:30 on the 30th day of February (which is a non-existent date, so this job will never run for now in prod)
      environment:
        JOB_NAME: DATABASE_MAINTENANCE
        REFRESH_FLAG: "1"
    global:
      environment: prod
      tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
      jobKind: CronJob
