apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../base/workload-identity
  - ../apim-marketplace/apim-marketplace.yaml
  - ../apim-marketplace-web/apim-marketplace-web.yaml
namespace: apim
