apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: cath
  namespace: cath
spec:
  resourceID: "/subscriptions/1c4f0704-a29e-403d-b719-b90c34ef14c9/resourcegroups/managed-identities-aat-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/cath-aat-mi"
  clientID: "44cc0551-c274-4f95-a980-dba76fe70fda"
