apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: cath
  namespace: cath
spec:
  type: 0

---

apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: cath-binding
  namespace: cath
spec:
  azureIdentity: cath
  selector: cath
