apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ccd-case-activity-api
spec:
  releaseName: ccd-case-activity-api
  values:
    nodejs:
      java:
      image: hmctsprod.azurecr.io/ccd/case-activity-api:prod-f4a29ad-20260328000355 #{"$imagepolicy": "flux-system:demo-ccd-case-activity-api"}
      environment:
        DUMMY_VAR_TO_REDEPLOY: 2
