apiVersion: v1
data:
  token: ENC[AES256_GCM,data:A3dz2nu5uchkeEdXK7TC1Mnp438E8hr+xnFscCbnLn5jCIzqhGavD51EoQd1VJ/dvOmmXIZg+ETF3pix/sI2CsVn9lDLCxGQD6r3nw==,iv:hRjeA49lwb47EJ9J53LgQdfxy8gPS66J8H/ncfRWonE=,tag:c0abIe53gIFcdXg7KOWQpQ==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: slack-token
  namespace: ${NAMESPACE}
type: Opaque
sops:
  azure_kv:
    - created_at: "2026-06-03T09:38:59Z"
      enc: oJSsWsBOBSueccn_8zX5MDG5ID6BVkO-JS91y_NX0YHyABKOHRbfG-igk8NjeGEyNe30hEwcZJkJC5cc-CoTjI4_OIRF7ZT7GZhB7kc8c1StUg-qPY6BqHAt8oEAwI53b0SQFC1qX_5l-TYUsouzEad12N1aHiT-trKY0LRKLPTGk0iFl_FDMY82dv-fvXHyo4qLYvsx2imHarfFQVWmsMmWQEP_hs-5x6qTd8J99mPfliikhev4B32tfQN2IzqaaRR-OVzrVqjUiZuJmmq2UxNmDRg1pOJuxjTNcYnlFoDM3kEj5szRuQPdkeLWqCRRjLWa3yp9dgbBQRdNyD0U2g
      name: sops-key
      vault_url: https://dtscftptlsbox.vault.azure.net
      version: b8a4ffea7a5041318ec2d7623a298d0c
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-03T09:39:02Z"
  mac: ENC[AES256_GCM,data:tIDN9qdyfm6+YtfQBO0GwHUHkYkCqEqj+Mrhh8pSNdMSHly8sngj0ILPb49+NglmuBGVjuxNNIzdu03EBY25WP1S2FaczKvG6ZJMJ1g/ehFy04DL4SwYFXsfBZAKFlUF8XTJCcSS9VI42ZkOu1EUlXgQ2JdqI1XZU4+sE9PiYrs=,iv:vqo/BWZErc7iNzYgI6gFQ9W1l5kO8nJpuf3nD6xUV3I=,tag:r1yqDRjuDzCus2ECk99WFw==,type:str]
  version: 3.13.1
