apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: cath
type: Opaque
stringData:
  PASSWORD: ENC[AES256_GCM,data:GUoXHbqgOeVwtdoeRrDk7Xhax1Jqe5EH,iv:kDzv6kJBoSe/XnWYYlTn9M3b0E8uCUEf5W/JVCiI1no=,tag:/xZyveL04HB4HgRkw11bAg==,type:str]
  HOST: ENC[AES256_GCM,data:6t0hpAGAKcnqryvftsR5Bby/3cicClpm1qmlGKlgMqjPHIXV5LS+nQ==,iv:y1RfquKJhIOBFPpAyuk1FB0ZTQ00uULZKNHj3a7jg1E=,tag:WvnlGtmAZkocVudgGSFPzQ==,type:str]
  USER: ENC[AES256_GCM,data:UygUAMU=,iv:+fnzO5cwXThMrO0gIEd4BlEaz7vvpLypoY0QmgmYkoQ=,tag:2B+i843+M/4mTU4L+qGVSA==,type:str]
  PORT: ENC[AES256_GCM,data:MqZ9Fw==,iv:BNAyrjEdnPr6wrKNk9Hzf3r3mcsAXUbxJRtQ4OW2gC4=,tag:XxkKxHkPdu+PQzll+bhRww==,type:str]
sops:
  azure_kv:
    - created_at: "2026-06-18T11:41:33Z"
      enc: WT6esWWwu_HiYMXT2_lGN8fznz24RruaFWpEtSiAGodop99CQh7Do7bjaFeeZkpop0PgRoiLGQoRKp_3rkwJ1JgVZecRh4jds65LheuAAMazF4VfZ4lpoqRj5XS4cKY0VB3WAD5dCuePJOuC48iD9Xc3d6ObARgCYtelhf6uNPkjQxedtr7oo_47xL-2y6skorULBst9Z1SglA-dcbHMjT9itOO5CbsFNURf2IsvNp8-AuG5MkCQaWDDe8gaL2MY7476oIY26jS7uQWEoluCwao-DNUdWK6VAYEI1PzNLBUKmgG7nTTO4OCmOi0pfT0iilr9aqZBhZPllNe5PihoVQ
      name: sops-key
      vault_url: https://dcdcftappsdevkv.vault.azure.net
      version: aedb9ea38954430ca1d0a46ed589c049
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T11:41:33Z"
  mac: ENC[AES256_GCM,data:8haT1Y1vAmE/gDhAcPiEIBJpNmi+Xlmy/6gRrUlZ/RcoiSWzY9XuCkm6O3KIAQWhm+2qafdQOh1bISBq4zzToShvfcxu1dZZ2E4z9KdyXekN5q+//XZXGRJXplDwLYejqpPznBJG+KMuyRgJx93A0ZzSf90Cure++346eOVZ9ds=,iv:JmeshEwuV13z6enIL67EkAZ/zj+K0clgKTJ3EqONvOk=,tag:8EVGykH1e9Vrdt/l++dWjg==,type:str]
  version: 3.13.1
