apiVersion: v1
data:
  PASSWORD: ENC[AES256_GCM,data:OZANL7YRvCqpGG5Rqs3XN4FWNRLPf3sA,iv:t0S9zod0Kgahb4jAn30SAtoFe/A4vdGjCQcOkE3ZgmI=,tag:ZRNyj6xcZNpjAgHfLRC8bw==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: pt
type: Opaque
sops:
  azure_kv:
    - vault_url: https://dcdcftappsdevkv.vault.azure.net
      name: sops-key
      version: aedb9ea38954430ca1d0a46ed589c049
      created_at: "2026-05-06T11:22:12Z"
      enc: pdA4cCqekut8mngKeBCapm0tRwhvkfNuwS0PMpC3H12Qn2hcO9SBHmm1nWxRyLdnYKAtAwNbjDQ_AmnL_r5a8cICraf4bxqyAZSfmqKVdzA2oTbfaRp7K00kulrEsO07FFanCJlOWiMtCMmFSqk9klmRAo8qo4UhiZVIGB07EAkuXnpJ_uqn45m5WoneF-0x8q6en0kvK_pry4OK8vhajCwlF7vmjwdq4enzILgVlJ_tShj8ioaLK9H3ax-YdR1AB0S6CNATZQTh6qg6HsQ2TXkxAyMdZ1oh_4QCKE2i73vuGckvwZIDxGJhrBHE8s9VV2uWcNJsVjwXB9f7CuhVvA
  lastmodified: "2026-05-06T11:22:13Z"
  mac: ENC[AES256_GCM,data:LdFUJElFep35p6BsbA2dBmnwkFWOZVflkrCKqI2PUhFlg9IxE94EIUTk6dj+fLmU99gQEZ8iHop11UgsuyIsnTEIyDjhs3A+AGYZ1I0EtrF2/3SsquX366FAP9dHwMy8F2nu9Xv5XYg4GRcz0gqD7ylpiCqBCWkpOihj6YO77hw=,iv:YntFQiEx8GUisb82wBDw8Cn/0S27dSDSBGNiFqYPDqs=,tag:0P/COTa6SwVNaRXdMBqaig==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
