apiVersion: managedidentity.azure.com/v1api20220131preview
kind: FederatedIdentityCredential
metadata:
  name: dtsse-services-${WI_CLUSTER}-fic
  namespace: dtsse
spec:
  owner:
    name: dtsse-services-prod-mi
  audiences:
    - api://AzureADTokenExchange
  issuer: ${ISSUER_URL}
  subject: system:serviceaccount:dtsse:dtsse-services
