apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fees-register-api-int
spec:
  releaseName: fees-register-api-int
  values:
    java:
      image: hmctsprod.azurecr.io/fees-register/api:pr-655-1eced3c-20260310121220 #{"$imagepolicy": "flux-system:demo-int-fees-register-api"}
      imagePullPolicy: Always
      environment:
        DUMMY_RESTART_VAR: false
        POSTGRES_NAME: postgresqldb2
