apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../cath-web/image-repo.yaml
  - ../cath-web/image-policy.yaml
  - ../cath-api/image-repo.yaml
  - ../cath-api/image-policy.yaml
  - ../cath-crons/image-repo.yaml
  - ../cath-crons/image-policy.yaml
  - ../cath-postgres/image-repo.yaml
  - ../cath-postgres/image-policy.yaml
