apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../cath-web/image-repo.yaml
  - ../cath-web/image-policy.yaml
  - ../cath-web/demo-image-policy.yaml
  - ../cath-web/perftest-image-policy.yaml
  - ../cath-api/image-repo.yaml
  - ../cath-api/image-policy.yaml
  - ../cath-api/demo-image-policy.yaml
  - ../cath-api/perftest-image-policy.yaml
  - ../cath-crons/image-repo.yaml
  - ../cath-crons/image-policy.yaml
  - ../cath-crons/demo-image-policy.yaml
  - ../cath-crons/perftest-image-policy.yaml
  - ../cath-postgres/image-repo.yaml
  - ../cath-postgres/image-policy.yaml
  - ../cath-postgres/demo-image-policy.yaml
  - ../cath-postgres/perftest-image-policy.yaml
