apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: api
spec:
  values:
    base:
      image: hmctsprod.azurecr.io/et-pet/api:prod-87f7f8d-20260724102831 #{"$imagepolicy": "flux-system:demo-et-pet-api"}
    sidekiq:
      image: hmctsprod.azurecr.io/et-pet/api:prod-87f7f8d-20260724102831 #{"$imagepolicy": "flux-system:demo-et-pet-api"}
    solid-queue:
      image: hmctsprod.azurecr.io/et-pet/api:prod-87f7f8d-20260724102831 #{"$imagepolicy": "flux-system:demo-et-pet-api"}
