apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: api
spec:
  values:
    base:
      image: hmctsprod.azurecr.io/et-pet/api:pr-762-48b34fb-20260805145659 #{"$imagepolicy": "flux-system:demo-et-pet-api"}
    sidekiq:
      image: hmctsprod.azurecr.io/et-pet/api:pr-762-48b34fb-20260805145659 #{"$imagepolicy": "flux-system:demo-et-pet-api"}
    queue-worker:
      image: hmctsprod.azurecr.io/et-pet/api:pr-762-48b34fb-20260805145659 #{"$imagepolicy": "flux-system:demo-et-pet-api"}
