apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rd-location-ref-data-load
spec:
  values:
    job:
      schedule: "50 10 * * *"
      image: hmctsprod.azurecr.io/rd/location-ref-data-load:prod-7c7ef1a-20260722201856 #{"$imagepolicy": "flux-system:demo-rd-location-ref-data-load"}
      environment:
        DELETE_ORG: false
