apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rd-location-ref-data-load
spec:
  values:
    job:
      schedule: "30 12 * * *"
      image: hmctsprod.azurecr.io/rd/rd-location-ref-data-load:prod-00d330c-20260611085923 #{"$imagepolicy": "flux-system:demo-rd-location-ref-data-load"}
      environment:
        DELETE_ORG: false