apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rd-location-ref-data-load
spec:
  values:
    job:
      schedule: "00 08 * * *"
      image: hmctsprod.azurecr.io/rd/location-ref-data-load:prod-15bd5e8-20260722140735 #{"$imagepolicy": "flux-system:perftest-rd-location-ref-data-load"}
      environment:
        DELETE_ORG: true
