apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: div-cms
  namespace: divorce
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/div/cms:prod-346ba56-20260326110024 #{"$imagepolicy": "flux-system:div-cms"}
      environment:
        IDAM_API_BASEURL: "https://idam-api.aat.platform.hmcts.net"
      prometheus:
        enabled: true
