apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
<<<<<<<< HEAD:apps/sptribs/sptribs-cron-trigger-system-clean-documents/aat/01.yaml
  name: sptribs-cron-trigger-system-clean-documents
spec:
  releaseName: sptribs-cron-trigger-system-clean-documents
========
  name: sptribs-cron-clean-further-documents
spec:
  releaseName: sptribs-cron-clean-further-documents
>>>>>>>> 2c100e80f858d266a3e6345f1939b5462c1bf093:apps/sptribs/sptribs-cron-clean-further-documents/aat/01.yaml
  values:
    job:
      schedule: "0,10,20,30,40,50 * * * *"
    global:
      jobKind: CronJob
      enableKeyVaults: true
      tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
      environment: aat
