apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ccpay-notifications-service
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/ccpay/notifications-service:pr-717-e3eb5e2-20260527095511 #{"$imagepolicy": "flux-system:demo-ccpay-notifications-service"}
      environment:
        DUMMY_VARIABLE: false
        LIBERATA_BASE_URL: "https://lascustomerportaluat.liberata.com"
