apiVersion: v1
data:
    apiToken: ENC[AES256_GCM,data:1VNmIFlh3Tj2O18JSqsDQptpl0CbZ8w8XNbXZytIwvzJ+af8gjqLrv+F2tAyzZSHe2h/buZZG/h5gKl138Y3ufhsiRZCwqIKBAsgdJfgpBM2uj7pIJoTtAk6iXdetmnA5MxNoF6WBL2sL3iAXtwRFe0kHNRyFMoCjvdNMkx83rM=,iv:Up4i//2KZxnDJU6e4ioSrrChM5A1hbkxMkqLR55gO9c=,tag:fscVbKWBHR19IpwKj3D66g==,type:str]
    dataIngestToken: ENC[AES256_GCM,data:d7xonXnSdLsVyqrzSa0Z6U+/cZCyrM/M/PV5UKnALLexVbAy0QF9KcjshtTmzq5GqyV1CDQ+t2NLL3RPdjnO2A2v3ZARo8FPA6/DUWoQox9aUmpZq4JnC4x1gz652CGmZxa6wDuShDIuSKMHbklYuZ/0yvLlhxdEh1sWmYVfEjI=,iv:3/JgreJ/35Wzoi8Nosl1pvHjqMobQ5YkF0EnrHWB5g8=,tag:sImMrjjBiNkaOH/oL8ZU7Q==,type:str]
kind: Secret
metadata:
    name: dynakube
    namespace: dynatrace
type: Opaque
sops:
    azure_kv:
        - created_at: "2026-03-10T10:59:11Z"
          enc: X0d8FKsuSM0AHFVGKGD8IJFYfJkD3FntyV1RHMP0_xnUFXgW8zXI8ETXxpAIERXcBL8SbG_g8RJ3JQG6UfX9cJRWZKb1hCpTHxMeINmm6taquQBVM6hvpgIFVCIufOazcCJprIESwP5jSh1KsMK435AnAzgcWg95KsiqcHacOx4m-Wu8nPGjLd7g7g4vLQYOPy2r-cyt645zKTUBl0BWSSrAwXv04Xr9M00L3-4YIRmjvlJnOsCMwHeNjvQw8j4Ud-QTckD3svVhhidQIyqg2OrsYnjLSaWRh74U7uEWAyUzp5VBIrgNdQ8I9oU7XkHCbrFdTyUeZFq7PjqIDpRDfA
          name: sops-key
          vault_url: https://dcdcftappsdemokv.vault.azure.net
          version: 7a5cc0c79b02466c86bc594c431e00f7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T11:34:07Z"
    mac: ENC[AES256_GCM,data:odajMdIEcPEPdmgObY6MD8cZZyle4ZbXlLpsrlBk8KPFHlq40fFdE0UxNmFSvqzxhPk+zwoJxkVWvRxJLXaCE74f8FEyZBrxJ1EJpkh3FkZOPCAF07/DkdG8cq+SzqVu6V9yn0uzE6cuVAxHeK7LgeEPqgAB5dgNuEh+7C2xH6A=,iv:KGUncNI9x/PqSg1UcxO0/IHE3AQ+rKlXppIuSc/6Ds8=,tag:q+d9TedggG1v9EtTfPFzwQ==,type:str]
    version: 3.13.3
