apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apim-marketplace
spec:
  values:
    java:
      ingressHost: apim-marketplace.demo.platform.hmcts.net
      keyVaults:
        apim:
          secrets:
            - name: marketplace-POSTGRES-USER
              alias: POSTGRES_USER
            - name: marketplace-POSTGRES-PASS
              alias: POSTGRES_PASS
            - name: marketplace-POSTGRES-HOST
              alias: POSTGRES_HOST
            - name: marketplace-POSTGRES-PORT
              alias: POSTGRES_PORT
            - name: marketplace-POSTGRES-DATABASE
              alias: POSTGRES_DATABASE
