apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apim-marketplace
spec:
  values:
    global:
      enableKeyVaults: true
    java:
      ingressHost: apim-marketplace-sandbox.service.core-compute-sandbox.internal
      workloadClientID: "775648eb-07db-4354-90f6-f0bca549341b"
      environment:
        APPLICATIONINSIGHTS_ENABLED: "false"
        APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=00000000-0000-0000-0000-000000000000"
      keyVaults:
        apim-sbox:
          excludeEnvironmentSuffix: true
          secrets:
            - name: marketplace-POSTGRES-USER
              alias: POSTGRES_USER
            - name: marketplace-POSTGRES-PASS
              alias: POSTGRES_PASS
            - name: marketplace-POSTGRES-HOST
              alias: POSTGRES_HOST
            - name: marketplace-POSTGRES-PORT
              alias: POSTGRES_PORT
            - name: marketplace-POSTGRES-DATABASE
              alias: POSTGRES_DATABASE
