apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wa
resources:
- ../base
- ../../wa-messages-reset-problem-messages/wa-messages-reset-problem-messages.yaml
patches:
- path: ../../wa-messages-reset-timestamp-problem-messages/prod.yaml
- path: ../../wa-task-batch-reconfiguration/prod.yaml
- path: ../../wa-task-batch-reconfiguration-failure/prod.yaml
- path: ../../wa-task-batch-termination/prod.yaml
- path: ../../wa-task-batch-termination-failure/prod.yaml
- path: ../../wa-task-batch-initiation-failure/prod.yaml
- path: ../../wa-messages-reset-problem-messages/prod.yaml
- path: ../../wa-task-batch-initiation/prod.yaml
- path: ../../wa-task-batch-ad-hoc-pending-termination/prod.yaml
- path: ../../wa-task-batch-update-search-index/prod.yaml
- path: ../../wa-messages-find-problem-messages/prod.yaml
- path: ../../wa-messages-set-processed-state-messages/prod.yaml
- path: ../../wa-case-event-handler-clean-up-messages/prod.yaml
- path: ../../wa-task-batch-replication-check/prod.yaml
