apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ccd
resources:
  - data-store
  - definition-store
  - logstash-config.yaml
  - logstash-main
  - logstash-civil
  - logstash-fpl
  - logstash-cmc
  - logstash-divorce
  - logstash-ethos
  - logstash-probate
  - logstash-probateman
  - logstash-sscs
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: ccd-elasticsearch-app-logstash.*
    patch: |-
      - op: replace
        path: /spec/values/envFrom
        value:
          - secretRef:
              name: logstash-secret
          - configMapRef:
              name: ccd-elasticsearch-app-logstash-config
      - op: add
        path: /spec/values/persistence
        value:
          enabled: true
      - op: add
        path: /spec/values/volumeClaimTemplate
        value:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: ccd-elasticsearch-app-logstash-probateman
    patch: |-
      - op: replace
        path: /spec/values/envFrom
        value:
          - secretRef:
              name: logstash-secret
          - secretRef:
              name: probatemandb
          - configMapRef:
              name: ccd-elasticsearch-app-logstash-config
