apiVersion: v1
kind: ConfigMap
metadata:
  name: ccd-elasticsearch-app-logstash-config
data:
  ES_HOST0: http://ccd-es-app-ithc-0.service.core-compute-ithc.internal:9200
  ES_HOST1: http://ccd-es-app-ithc-1.service.core-compute-ithc.internal:9200
  ES_HOST2: http://ccd-es-app-ithc-2.service.core-compute-ithc.internal:9200
  ES_HOST3: http://ccd-es-app-ithc-3.service.core-compute-ithc.internal:9200
