apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unprocessed-payment-update
spec:
  values:
    job:
      image: "hmctsprod.azurecr.io/payment/jobs:prod-f87208b-20260528085425" #{"$imagepolicy": "flux-system:ithc-unprocessed-payment-update"}
    java:
      environment:
        DUMMY_VARIABLE: true
