apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: docmosis
spec:
  values:
    ingressHost: docmosis.preview.platform.hmcts.net
    image: hmctsprod.azurecr.io/docmosis:preview-8cae649-1191760 #{"$imagepolicy": "flux-system:preview-docmosis"}
    disableTraefikTls: false
