apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: docmosis
spec:
  values:
    ingressHost: docmosis.preview.platform.hmcts.net
    image: hmctsprod.azurecr.io/docmosis:preview-ceb1aaa-1046811 #{"$imagepolicy": "flux-system:preview-docmosis"}
    disableTraefikTls: false
