apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: docmosis
spec:
  values:
    ingressHost: docmosis.sandbox.platform.hmcts.net
    image: hmctsprod.azurecr.io/docmosis:sandbox-6834bde-1229393 #{"$imagepolicy": "flux-system:sandbox-docmosis"}
    environment:
      DOCMOSIS_RENDER_USEURL: https://docmosis.sandbox.platform.hmcts.net
      DOCMOSIS_TORNADO_RENDER_USEURL: https://docmosis.sandbox.platform.hmcts.net
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: docmosis-base
              spec:
                template:
                  metadata:
                    annotations:
                      azure.workload.identity/inject-proxy-sidecar: "true"
  chart:
    spec:
      chart: base
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: hmctsprod-oci
        namespace: flux-system
