apiVersion: v1
data:
    apiToken: ENC[AES256_GCM,data:1ZhN053sXpkxDTmWbKPEaFTAP8yLpWO04ZoYWbcvb7iyI8Rvdr3+9C4Tq/G9riTtrBSALmS/YgO1P5E88AqK6VujG/FVPr1Nrl84RrLxbomcTcNjmSGwBXNQUNPqeWsp0sB3jy8QKQ36NJcKO/AqGsiJ7eTqrChB/a7TGsnDUiU=,iv:VxGWly+5W8G9dqOL1t8IBtpiA4ZQ5PiYQkeaxt6AW1o=,tag:hnemvAqWNrzQvY62byHqmg==,type:str]
    dataIngestToken: ENC[AES256_GCM,data:aEdN5z808LDzvkzAs0/2zvhdCMLUMX5VazCquBauUijDYzJ3haw3p7ix2i+XnRXTnrYCBuS2pTS0Td9G3h6fYYhIUcej04fk1vbFXvU83pzc4GN2gIy+oqEF9GAwkErtzGkmO2rOjtJzWd2SEpQ+fSg7fKbBv+B2v2CbmSQSOSM=,iv:TWzTHkOQPlZnQv6wNmPZ3r2OD7EX7uNiHoRxRf+N5AA=,tag:hiPEEY00kaESQT2DXBE4ZA==,type:str]
kind: Secret
metadata:
    name: dynakube
    namespace: dynatrace
type: Opaque
sops:
    azure_kv:
        - created_at: "2023-02-15T13:20:02Z"
          enc: BekS7NWnO7NVFTasLWEZBorIyxJ12eXEoP8KTkzCtFCFggjA1eedh3Vvm-OLjSHLwaxDIiHjwhvnQoELe4ZAbwkQq-E8-O80BvVKCouzEOyEIXklbiELkJLgIBthjGSJwsTjYinT6ZNjAoHi8D42qfdR7ee47gwvLBAjI5jTJ54IBcoheiCkxToQ7YaNiMoE5ar27j-F7byJPlJ8-7JJJoMudcm9ZvG-LzbRggiH5jR5kKKElE8wqdLG5eRtrbrrj--qkV2AEmUpcu0a0HvxzNtDo_Xr_ytc-FGSZtwey6J70MT0AKoZfyKfohnG7hMZIMPfp2PrDsn1c_D1b7SiZg
          name: sops-key
          vault_url: https://dcdcftappstestkv.vault.azure.net
          version: c65ceab03e384b048a3002485b9656b8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T13:18:13Z"
    mac: ENC[AES256_GCM,data:gQfSCl25Qg9m8xkEK2xwpEnU8zGLCuVVYw/de3ggzFrsXKUX9PesEGEwKppB+KX1ywZktFExZrWz1nSY3sgw5XNOEO042anB62JKhl6/kej+Rjs609d+8SLLF2VGlXB9MQmi/oznw/rVuIeQ6tZpn75w+UnzAcCuprYMdPn3qhA=,iv:Wtc1rcj9jT9h4bq8jLzsfUZoYK9eHZgYBTPwtBYwjPk=,tag:xOnmrW6OWJ5jj+twoYuVJw==,type:str]
    version: 3.13.3
