apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ts-translation-service-int
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/ts/translation-service:prod-0b93cd7-20260917145146 #{"$imagepolicy": "flux-system:ts-translation-service"}
