apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ts-translation-service-int
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/ts/translation-service:prod-d2b77ac-20260602181218 #{"$imagepolicy": "flux-system:ts-translation-service"}
