apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ts-translation-service-int
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/ts/translation-service:prod-d8be6b7-20260527190233 #{"$imagepolicy": "flux-system:ts-translation-service"}
