apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: expressjs-monorepo-template-api
spec:
  releaseName: expressjs-monorepo-template-api
  interval: 5m
  values:
    nodejs:
      releaseNameOverride: expressjs-monorepo-template-api
      image: hmctsprod.azurecr.io/dtsse/expressjs-monorepo-template-api:prod-3a51ceb-20260507173737 # {"$imagepolicy": "flux-system:expressjs-monorepo-template-api"}
  chart:
    spec:
      chart: expressjs-monorepo-template-api
      version: ">=0.0.1-0"
      sourceRef:
        kind: HelmRepository
        name: hmctsprod-oci
        namespace: flux-system
      interval: 1m
