apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: et-sya
  annotations:
    hmcts.github.com/prod-automated: disabled
spec:
  releaseName: et-sya
  values:
    nodejs:
      image: hmctsprod.azurecr.io/et/sya:prod-78f1cb8-20260605083644 #{"$imagepolicy": "flux-system:et-sya"}
      ingressHost: et-sya.demo.platform.hmcts.net
