apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: et-sya
  namespace: et
spec:
  releaseName: et-sya
  values:
    nodejs:
      image: hmctsprod.azurecr.io/et/sya:pr-2377-eb1d1de-20260601145113 #{"$imagepolicy": "flux-system:ithc-et-sya"}
      ingressHost: et-sya.ithc.platform.hmcts.net
      environment:
        ET_SYA_API_HOST: 'http://et-cos-ithc.service.core-compute-ithc.internal'
        TRIGGER_RESTART: 0
        HMCTS_ACCESS: 'true'
