apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: et-sya
  namespace: et
spec:
  releaseName: et-sya
  values:
    nodejs:
      image: hmctsprod.azurecr.io/et/sya:prod-ae64ebd-20260316124310 #{"$imagepolicy": "flux-system:et-sya"}
      ingressHost: et-sya.ithc.platform.hmcts.net
