apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: et-sya
  namespace: et
spec:
  releaseName: et-sya
  values:
    nodejs:
      image: hmctsprod.azurecr.io/et/sya:prod-fd58f34-20261006091743 #{"$imagepolicy": "flux-system:ithc-et-sya"}
      ingressHost: et-sya.ithc.platform.hmcts.net
      environment:
        MANAGE_ORG_URL: 'https://manage-org.ithc.platform.hmcts.net'
        MANAGE_CASE_URL: 'https://manage-case.ithc.platform.hmcts.net'
        HMCTS_ACCESS: 'true'
