apiVersion: v1
data:
    PASSWORD: ENC[AES256_GCM,data:jXsFVwKQQLakibk8QbBvnmK7yc5SwvDS,iv:DD8o+j37QXjTeCPw8MhhJ73tgyvWUFKo+ivcoVp9PRs=,tag:WqOm0/KW39BNAsh7wCWWKA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: postgres
    namespace: tax-tribunals
type: Opaque
sops:
    azure_kv:
        - created_at: "2026-05-19T09:08:20Z"
          enc: muLJGP8CEBxpFpnQlYSs2NQcyGtUaXqiTIYGUB4ZkBS31ZHK9gwmyk6oDMBB49Zc80ExPrvlRvoTX2VqqoA3wQKsBndQt1-9uDWT8-bR_D0WMn4fvsw7Eonzi1qZgiZfTCbEpy7kNVhKmUEHwgkzYh6Q0BpdiLMZq9EsQelxpY_Ey55hAqskMkYNnEn9Uok3N0yTDWEakfzfQeq8XVEPEqz796Y3ZnU3xA63Iojlt9ru1vHOm4Y6XdfZ3hvO0W7wMK38b5dYOWWJOVClGE_wY3eAnC2Ma5oZb2cunst7TikTJhW66q4OnDUNs5A2K90Q-FWqq39aKjdCWDnt9wmHJQ
          name: sops-key
          vault_url: https://dcdcftappsdevkv.vault.azure.net
          version: aedb9ea38954430ca1d0a46ed589c049
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T09:08:22Z"
    mac: ENC[AES256_GCM,data:oGW6Ju4SpZAjRfc9gssNgB/zCo3CGBzSlr/WZ7Y+HcVGN5iSA735kt1gQ25o7MAGf8AImIjC+g+3p3GtG3fF0qGJiBdr6VjmpFJIBAq2dzm9bVdsOhYejsdDeh4A0o0ZnKjv1LiCAErcCxiTfMuUetgVvOrjXeAeP63bOV33+is=,iv:0L/+TehXXOYyv1NXJP2NwBsiw3+cOv1wgbITDfG3hpU=,tag:acmUW5NUAaPgr2KC9S3Q/Q==,type:str]
    version: 3.13.1
