apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wa
resources:
- ../base
patches:
- path: ../../wa-task-batch-reconfiguration/aat.yaml
- path: ../../wa-task-batch-reconfiguration-failure/aat.yaml
- path: ../../wa-messages-reset-timestamp-problem-messages/aat.yaml
- path: ../../wa-task-batch-termination/aat.yaml
- path: ../../wa-task-batch-termination-failure/aat.yaml
- path: ../../wa-task-batch-initiation-failure/aat.yaml
- path: ../../wa-messages-reset-problem-messages/aat.yaml
- path: ../../wa-task-batch-initiation/aat.yaml
- path: ../../wa-task-batch-maintenance-camunda-task-clean-up/aat.yaml
- path: ../../wa-task-batch-ad-hoc-pending-termination/aat.yaml
- path: ../../wa-task-batch-update-search-index/aat.yaml
- path: ../../wa-task-batch-replication-check/aat.yaml
- path: ../../wa-messages-find-problem-messages/aat.yaml
- path: ../../wa-messages-set-processed-state-messages/aat.yaml
- path: ../../wa-case-event-handler-clean-up-messages/aat.yaml
