apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ecm-consumer
  namespace: ethos
spec:
  releaseName: ecm-consumer
  values:
    java:
      image: hmctsprod.azurecr.io/ethos/ecm-consumer:prod-bb885e3-20260311112038 #{"$imagepolicy": "flux-system:ecm-consumer"}
