apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../runner-controller/helmrepo.yaml
  - ../runner-controller/controller.yaml
  - ../sups/sups-caps.yaml
namespace: github-arc
