apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: idam-hmcts-access
  namespace: idam
spec:
  releaseName: idam-hmcts-access
  values:
    nodejs:
      environment:
        SSO_AZURE_DOMAIN: 'azure.keycloak.sso'
        SSO_MOJ_DOMAIN: 'moj.keycloak.sso'
