apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: idam-hmcts-access
  namespace: idam
spec:
  releaseName: idam-hmcts-access
  values:
    nodejs:
      environment:
        SSO_CALLBACK_BASE_URL: 'https://idam-web-public.ithc.platform.hmcts.net'
