apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: idam-hmcts-access
  namespace: idam
spec:
  releaseName: idam-hmcts-access
  values:
    nodejs:
      environment:
        SSO_CALLBACK_BASE_URL: 'https://idam-web-public.ithc.platform.hmcts.net'
        SSO_FUNCTIONAL_DISPLAY_NAME: Functional domain-routing test    
        SSO_FUNCTIONAL_DOMAIN: functional.test    
        SSO_FUNCTIONAL_LOGIN_URL: /auth/functional-test-sso/login
