apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: idam-hmcts-access
  namespace: idam
spec:
  releaseName: idam-hmcts-access
  values:
    nodejs:
      image: hmctsprod.azurecr.io/idam/hmcts-access:pr-1667-1154ae5-20260723104359
      pdb:
        enabled: false
      replicas: 1
      ingressHost: hmcts-access.sandbox.platform.hmcts.net
      disableTraefikTls: true
      environment:
        PASSWORD_RESET_V2_ENABLED: true
        STRATEGIC_SERVICE_URL: 'https://idam-api.sandbox.platform.hmcts.net'
        STRATEGIC_TESTING_URL: 'https://idam-testing-support-api.sandbox.platform.hmcts.net'
