apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xui-ao-webapp
spec:
  values:
    nodejs:
      replicas: 2
      memoryLimits: "2048Mi"
      memoryRequests: "1024Mi"
      cpuLimits: "2000m"
      cpuRequests: "1000m"
      ingressHost: administer-orgs.perftest.platform.hmcts.net
      environment:
        DUMMY_VAR: true
        FEATURE_OIDC_ENABLED: true
        USER_TIMEOUT_IN_SECONDS: 1800
        DEBUG: xuiNode:*,-xuiNode:auth:s2s
        ISS_SERVICE: https://forgerock-am.service.core-compute-idam-perftest.internal:8443/openam/oauth2/realms/root/realms/hmcts
      image: hmctsprod.azurecr.io/xui/ao-webapp:pr-992-a6a6532-20260305134514 #{"$imagepolicy": "flux-system:perftest-xui-ao-webapp"}
