apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wa-reporting-frontend
spec:
  releaseName: wa-reporting-frontend
  values:
    nodejs:
      useInterpodAntiAffinity: true
      image: hmctsprod.azurecr.io/wa/reporting-frontend:prod-ae814ee-20260314011158 #{"$imagepolicy": "flux-system:wa-reporting-frontend"}
  chart:
    spec:
      chart: ./stable/wa-reporting-frontend
      sourceRef:
        kind: GitRepository
        name: hmcts-charts
        namespace: flux-system
      interval: 1m
