apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: labs-tmckillop95
  annotations:
    hmcts.github.com/image-registry: hmctssbox
spec:
  image: hmctssbox.azurecr.io/labs/tmckillop95
