apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xui-icp
spec:
  releaseName: xui-icp
  values:
    nodejs:
      replicas: 2
      image: hmctsprod.azurecr.io/xui/icp-api:prod-6d64942-20260909110321 # {"$imagepolicy": "flux-system:xui-icp"}
