apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xui-icp
spec:
  releaseName: xui-icp
  values:
    nodejs:
      replicas: 0
      image: hmctsprod.azurecr.io/xui/icp:pr-43-e04e2fc-20260902155605 # {"$imagepolicy": "flux-system:demo-xui-icp"}
