apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xui-icp
spec:
  releaseName: xui-icp
  values:
    nodejs:
      replicas: 2
      image: hmctsprod.azurecr.io/xui/icp-api:pr-67-47ef675-20260910143935 # {"$imagepolicy": "flux-system:demo-xui-icp"}
