apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xui-icp
spec:
  releaseName: xui-icp
  values:
    nodejs:
      replicas: 2
      image: hmctsprod.azurecr.io/xui/icp-api:pr-73-4ca40c5-20260916101212 # {"$imagepolicy": "flux-system:perftest-xui-icp"}
