apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xui-icp
spec:
  releaseName: xui-icp
  values:
    nodejs:
      replicas: 2
      image: hmctsprod.azurecr.io/xui/icp-api:pr-60-b973cd2-20260907103310 # {"$imagepolicy": "flux-system:perftest-xui-icp"}
