apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xui-icp
spec:
  releaseName: xui-icp
  values:
    nodejs:
      replicas: 2
      image: hmctsprod.azurecr.io/xui/icp-api:pr-62-afd6aa7-20260907120824 # {"$imagepolicy": "flux-system:perftest-xui-icp"}
