apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../deed-poll-api/image-repo.yaml
  - ../deed-poll-api/image-policy.yaml
  - ../deed-poll-admin/image-repo.yaml
  - ../deed-poll-admin/image-policy.yaml
