---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: labs-harveymoj-nodejs
  namespace: labs
spec:
  releaseName: labs-harveymoj-nodejs
  chart:
    spec:
      chart: ./stable/labs-harveymoj-nodejs
      sourceRef:
        kind: GitRepository
        name: hmcts-charts
        namespace: flux-system
      interval: 1m
  values:
    nodejs:
      image: hmctssbox.azurecr.io/labs/harveymoj-nodejs:latest # {"$imagepolicy": "flux-system:labs-harveymoj-nodejs"}
      disableTraefikTls: true
