apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: et-logstash
  namespace: et
spec:
  releaseName: et-logstash
  values:
    replicas: 1
    extraEnvs:
      - name: LS_LOG_LEVEL
        value: debug
