apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cath-crons
spec:
  releaseName: cath-crons
  values:
    job:
      image: hmctsprod.azurecr.io/cath/cath-crons:prod-d0b8064-20260921082129 # {"$imagepolicy": "flux-system:demo-cath-crons"}
