apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xui-icp-api
spec:
  releaseName: xui-icp-api
  values:
    nodejs:
      replicas: 0
      useInterpodAntiAffinity: true
      image: hmctsprod.azurecr.io/xui/icp-api:prod-0000000-19700101000000 # {"$imagepolicy": "flux-system:xui-icp-api"}
  chart:
    spec:
      chart: ./stable/xui-icp-api
      sourceRef:
        kind: GitRepository
        name: hmcts-charts
        namespace: flux-system
      interval: 1m
