apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: em-stitching-cron-old-audit-deletion
spec:
  releaseName: em-stitching-cron-old-audit-deletion
  values:
    job:
      applicationPort: 8095
      image: hmctsprod.azurecr.io/em/stitching:prod-28dd53a-20260812064416 #{"$imagepolicy": "flux-system:demo-em-stitching"}
      schedule: "*/15 17,18 * * *"
      environment:
        HISTORIC_AUDIT_NO_OF_RECORDS: 1000
    global:
      environment: demo
