apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: em-stitching-cron-old-audit-deletion
spec:
  releaseName: em-stitching-cron-old-audit-deletion
  values:
    job:
      applicationPort: 8095
    global:
      environment: ithc
