apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-collector
  namespace: monitoring
spec:
  values:
    ports:
      metrics:
        enabled: true
        containerPort: 8888
        servicePort: 8888
        protocol: TCP
    config:
      service:
        telemetry:
          metrics:
            address: 0.0.0.0:8888
      exporters:
        dynatrace:
          endpoint: "https://yrk32651.live.dynatrace.com/api/v2/metrics/ingest"
        otlphttp:
          endpoint: "https://yrk32651.live.dynatrace.com/api/v2/otlp"
