apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sscs-cor-frontend
  namespace: sscs
spec:
  values:
    nodejs:
      ingressHost: sscs-cor.demo.platform.hmcts.net
      image: hmctsprod.azurecr.io/sscs-cor/frontend:pr-1376-044fb2a-20261008093439 #{"$imagepolicy": "flux-system:demo-sscs-cor-frontend"}
      environment:
        DUMMY_PROPERTY: false
        IBC_NI_POSTCODES_FEATURE: true
        REDIS_CLUSTER: true
