apiVersion: v1
data:
    apiToken: ENC[AES256_GCM,data:bT7CxDCWF1rYDYu60X4AodRe83EsznLXv68LzDkeTq2ICO1gcCawmvMM/XtCTEJEf43+j0CnpA2P3OCATuXptu3KBbsl8qSrGarKc86Ml2YS54lbURZi/5AXs8nzKxye3Mbn6zqj1cYTFZ/zOXoRPfq8OUVC0Vb2BYea8YaM8Fs=,iv:4Ljnn65yQD6bHzVnr3jJJw6Aq0gxMLPRn2aJtbh5vKA=,tag:r9xk9kQSf5clwKqvNwTU5w==,type:str]
    dataIngestToken: ENC[AES256_GCM,data:RG/8wa0dAd6y2eym/lUXTViUizYX+nKUWoNZ/qKeyiokp54X2v2zdve9CaemkDpK9hUgI9BGtUiKrQlotxUpi5sO2FnV/J/9MkzWZAEr5W7IC2ilBnUbFx2AXErVgp1eIIQQbSUyNvxjGFvk4E2tXtZpyZ0AvZVmtR3BTXVnDk8=,iv:zbZPm3yK4dR45sm8jLEnGUXbNGjfeTQfjGX0oDy+p1s=,tag:F9RJaKsA3ikyk6TlXxM2qA==,type:str]
kind: Secret
metadata:
    name: dynakube
    namespace: dynatrace
type: Opaque
sops:
    azure_kv:
        - created_at: "2023-02-15T13:40:35Z"
          enc: FtTvpgI2pYULmW2pJWGCAI6fdTEgSjC_Pv8YSC37AoKZDDSGe62EmvxFhDlyJEvP7UDbbwq-Vs1COYRef7Wq5fG3G-yb2VxzP4XH-WAvapgJrhXSCgRpOYQzp98GbxeP8owf_mF_vnk0QtZuLT1fCGv-M0mb5aDcbuo0baT8YSMsTpVb-tpAsCHRqQ8TuOKqi8_QBgyiXx4X8aOly5FMBcPm4uK-v5tkxbKxFnFi8_G1wz5U3qBvfxa0GevSCVCGHvVLGyXagYZ6uEg_GFdFRrXMhxck76sllq7c2m8RZuQpYj_GWZWQyNrvCe-PeGrbMD_VEQoFF3epDYl3LS4J2A
          name: sops-key
          vault_url: https://dcdcftappsstgkv.vault.azure.net
          version: 04939605492d4c4384d4ed1343df61b2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T13:12:58Z"
    mac: ENC[AES256_GCM,data:CnKSLcz0en+biYmV0GqMRCkrIRCByLbURk7NqUJjZuD7s4RYzfTqb/mhftyYBDjCQjyVdIHhldoBo8aKgraqt5Io24hxzPWfnFv2XxerAiYQXtWg1ozszPq9+vWMx4ZJrCpqB7kUOJvpwE6ObTY7kIRdMRkqkDRXcXdtm37Ukfs=,iv:A5y1BwpK8csHIWJAq46+IZhxgjqhmJSRjl5bMfk3QFk=,tag:QnIVeY9lr5ajegYCyk5BTg==,type:str]
    version: 3.13.3
