apiVersion: dynatrace.com/v1beta6
kind: DynaKube
metadata:
  name: dynakube
  namespace: dynatrace
spec:
  apiUrl: https://yrk32651.live.dynatrace.com/api
  oneAgent:
    cloudNativeFullStack:
      annotations:
        cluster-autoscaler.kubernetes.io/enable-ds-eviction: "false"
      args:
        - --set-host-group=AAT_CFT
  # spec.templates.otelCollector.replicas is defined in the v1beta6 CRD schema as type: integer; if not specified will fail the type check
  templates:
    otelCollector:
      replicas: 0 # 0=disabled
