apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: em-icp
spec:
  values:
    nodejs:
      image: hmctsprod.azurecr.io/em/icp:pr-1510-2f2fd8a-20260501113819 #{"$imagepolicy": "flux-system:demo-em-icp"}
      environment:
        DUMMY_VAR: 1
        SERVICES_CCD_COMPONENT_API: https://gateway-ccd.{{ .Values.global.environment }}.platform.hmcts.net
