apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dtsse-github-metrics
spec:
  releaseName: dtsse-github-metrics
  values:
    nodejs:
      image: hmctsprod.azurecr.io/dtsse/github-metrics:prod-00ad4a9-20260909060442 #{"$imagepolicy": "flux-system:dtsse-github-metrics"}
    job:
      image: hmctsprod.azurecr.io/dtsse/github-metrics:prod-00ad4a9-20260909060442 #{"$imagepolicy": "flux-system:dtsse-github-metrics"}
  chart:
    spec:
      chart: dtsse-github-metrics
      version: ">=0.0.2"
      sourceRef:
        kind: HelmRepository
        name: hmctsprod-oci
        namespace: flux-system
      interval: 1m
