apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cmc-dg-docassembly
  namespace: money-claims
spec:
  releaseName: cmc-dg-docassembly
  interval: 1m
  chart:
    spec:
      chart: ./stable/dg-docassembly
      sourceRef:
        name: hmcts-charts
        kind: GitRepository
        namespace: flux-system
  values:
    java:
      image: hmctsprod.azurecr.io/dg/docassembly:prod-7dea7ae-20260330071849 #{"$imagepolicy": "flux-system:dg-docassembly"}
