apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ccd-logstash-sscs
  namespace: ccd
spec:
  releaseName: ccd-logstash-sscs
  values:
    replicas: 1
    logstashPipeline:
      01_input.conf: |
        input {
          jdbc {
            jdbc_connection_string => "${DATA_STORE_URL}"
            jdbc_user => "${DATA_STORE_USER}"
            jdbc_password => "${DATA_STORE_PASS}"
            jdbc_validate_connection => true
            jdbc_driver_library => "/usr/share/logstash/ccd/postgresql.jar"
            jdbc_driver_class => "org.postgresql.Driver"
            jdbc_default_timezone => "UTC"
            parameters => {
                        "jurisdiction" => "SSCS"
                        "claim_timeout" => "${LOGSTASH_QUEUE_CLAIM_TIMEOUT}"
                          }
            statement => "WITH candidates AS (SELECT q.id FROM case_data_logstash_queue q JOIN case_data cd ON q.case_data_id = cd.id WHERE q.case_data_id = cd.id  AND jurisdiction = :jurisdiction AND (q.claimed_at IS NULL OR q.claimed_at < clock_timestamp() - CAST(:claim_timeout AS interval)) ORDER BY q.id FOR UPDATE SKIP LOCKED LIMIT 1000), claimed AS (UPDATE case_data_logstash_queue q SET claim_token = md5(random()::text || clock_timestamp()::text), claimed_at = clock_timestamp() FROM candidates c WHERE q.id = c.id RETURNING q.id AS logstash_queue_id, q.case_data_id, q.claim_token) SELECT claimed.logstash_queue_id, claimed.claim_token, cd.id, created_date, last_modified, jurisdiction, case_type_id, state, last_state_modified_date, data::TEXT as json_data, data_classification::TEXT as json_data_classification, reference, security_classification, supplementary_data::TEXT as json_supplementary_data, version FROM claimed JOIN case_data cd ON claimed.case_data_id = cd.id"
            clean_run => false
            schedule => "* * * * * *"
          }
        }
