apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ia-home-office-mock-api
spec:
  values:
    java:
      ingressHost: ia-home-office-mock-api-ithc.service.core-compute-ithc.internal
      image: hmctsprod.azurecr.io/ia/home-office-mock-api:prod-1e69320-20260629165357 #{"$imagepolicy": "flux-system:ia-home-office-mock-api"}
