apiVersion: v1
data:
  token: ENC[AES256_GCM,data:JHEAT6EM0VUHHGuN3ogTDUPsVWw/W8hZ11cFEPe2GqEc8oQiXRvxXfEYhMdk2Iw0LvMrbCJqyIMsh16y76zP9ASMY74F8OnXI/eHog==,iv:PqU/UcyfU1UmxPBtUosaWaxSxdQKQGo0fNmcwdSsxKg=,tag:Mhk+eKPZRR77rdggYhuO6Q==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: slack-token
  namespace: ${NAMESPACE}
type: Opaque
sops:
  azure_kv:
    - created_at: "2026-06-02T16:40:11Z"
      enc: iTItC5Az5LPvR_x-YM4HT7bLHZKP2Nt2Z9elzh8Pgr0dLmBh8C7jsvT6yxo_iCHeiATneoToy4KIhWZdgRooATy_JAcosLtLrOvWyVi3h_lEzBksEGk9DUmW5RdhYt3EZ9yWFWJ3CGEHcaLnmbpgZl8PTe_qT-yQzLGEJ6_rNOu3cuqCiPAoCA6_SlFYUutci__IlI3knZxi4k59iwTgemRph9xppCBIJ4nn9Xq_5Msq9XbkQi938PHcMuZhzvYVvhfzMgQKuYj26vwhMnkMEg6f8fkTOZk26n2JMZ2m4rRRd6F47v03bi4m_Ij-tKLKseSWAuGHFEHfnv2nGEbsHA
      name: sops-key
      vault_url: https://dtscftptl.vault.azure.net
      version: b30650cb91de4bc095766db59efbd819
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T16:40:17Z"
  mac: ENC[AES256_GCM,data:wgpzggtScHAFoevWShc3WFC1EQrezv4/XW9AiE8eVtLPeoUX3svWatDES9vKI+B4RP4pweepxusVdMVvsh9MTkY1gn1NdVu+IAuKclq3HN8OqNddLFxgMWS/fU1RX1/rbSM6FAcHWAOXApYHYiG4mGDyxY6n3Abh8G0T1rXsHJk=,iv:Lve36qNmX66Y+dyKJ5YZ0MIirlXVRGoXaI3VLXk2WQc=,tag:ZUfNRIKa4BxBln1yjESYBA==,type:str]
  version: 3.13.1
