apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ccd-ac-int-definition-store-api
spec:
  releaseName: ccd-ac-int-definition-store-api
  values:
    java:
      image: hmctsprod.azurecr.io/ccd/definition-store-api:prod-6f7c1e5-20260928155210 #{"$imagepolicy": "flux-system:ccd-definition-store-api"}
