apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ccd-ac-int-definition-store-api
spec:
  releaseName: ccd-ac-int-definition-store-api
  values:
    java:
      image: hmctsprod.azurecr.io/ccd/definition-store-api:prod-ad5cd51-20260526160444 #{"$imagepolicy": "flux-system:ccd-definition-store-api"}
