apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../../rbac/nonprod-role.yaml
  - ../../rota-optimiser/rota-optimiser.yaml
  - ../../rota-worker/rota-worker.yaml
namespace: rota
patches:
  - path: ../../rota-resource/demo.yaml
  - path: ../../rota-worker/demo.yaml
  - path: ../../serviceaccount/demo.yaml
