apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dm-store
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/dm/store:prod-f99b79c-20260317085859 #{"$imagepolicy": "flux-system:demo-dm-store"}
      environment:
        ENABLE_TTL: false
        UPLOAD_BLOCK_SIZE: 8
        UPLOAD_MAX_CONCURRENCY: 10
        MAX_SINGLE_UPLOAD_SIZE: 100
