apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: sptribs-cron-migrate-case-documents-to-doc-table
spec:
  imageRepositoryRef:
    name: sptribs-cron-migrate-case-documents-to-doc-table
