apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hmc-admin-ui
spec:
  releaseName: hmc-admin-ui
  values:
    nodejs:
      replicas: 1
      ingressHost: hmc-admin-ui.demo.platform.hmcts.net
      image: hmctsprod.azurecr.io/hmc/admin-ui:pr-121-fad4022-20260904121501 #{"$imagepolicy": "flux-system:demo-hmc-admin-ui"}
      environment:
        DUMMY_VAR: 0
        IDAM_PUBLIC_URL: https://hmcts-access.demo.platform.hmcts.net
        HMC_ADMIN_UI_BASE_URL: https://hmc-admin-ui.demo.platform.hmcts.net
        HMC_CFT_HEARING_SERVICE_URL: http://hmc-cft-hearing-service-demo.service.core-compute-demo.internal
        SERVICES_S2S: http://rpe-service-auth-provider-demo.service.core-compute-demo.internal
