apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hmc-admin-ui
spec:
  releaseName: hmc-admin-ui
  values:
    nodejs:
      ingressHost: hmc-admin-ui.demo.platform.hmcts.net
      image: hmctsprod.azurecr.io/hmc/admin-ui:pr-121-e9a6d0d-20260826100558 #{"$imagepolicy": "flux-system:demo-hmc-admin-ui"}
      environment:
