apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pcq-loader
spec:
  releaseName: pcq-loader
  values:
    job:
      useInterpodAntiAffinity: true
      image: hmctsprod.azurecr.io/pcq/loader:prod-5b901c0-20260522123641 #{"$imagepolicy": "flux-system:pcq-loader"}
  chart:
    spec:
      chart: ./stable/pcq-loader
      sourceRef:
        kind: GitRepository
        name: hmcts-charts
        namespace: flux-system
      interval: 1m
