apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: probate-cron-smee-and-ford-extract
spec:
  releaseName: probate-cron-smee-and-ford-extract
  values:
    job:
      schedule: "0 * 31 2 *"
      useInterpodAntiAffinity: true
      image: hmctsprod.azurecr.io/probate/back-office:prod-a7789a7-20260529101816 #{"$imagepolicy": "flux-system:probate-back-office"}
      environment:
        TASK_NAME: SmeeAndFordExtractTask
        VAR_FV2: trigger-1
  chart:
    spec:
      chart: probate-cron
      version: 0.0.35
      sourceRef:
        kind: HelmRepository
        name: hmctsprod-oci
        namespace: flux-system
