apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../deed-poll-api/deed-poll-api.yaml
  - ../../../rbac/nonprod-role.yaml
namespace: deed-poll
patches:
  - path: ../../serviceaccount/aat.yaml
