apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: demo-missing-reports-cron-trigger-daily-checks
spec:
  imageRepositoryRef:
    name: missing-reports-cron-trigger-daily-checks
