apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: em-anno
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/em/anno:prod-c99f4b9-20260318092404 #{"$imagepolicy": "flux-system:demo-em-anno"}
      environment:
        TEST_VAR: refresh
