apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: em-anno
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/em/anno:prod-5666f3f-20260323090923 #{"$imagepolicy": "flux-system:demo-em-anno"}
      environment:
        TEST_VAR: refresh
