apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../fis-hmc-api/image-repo.yaml
  - ../fis-hmc-api/image-policy.yaml
  - ../fis-hmc-api/demo-image-policy.yaml
  - ../fis-hmc-api/perftest-image-policy.yaml
  - ../fis-hmc-api/ithc-image-policy.yaml