apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: et-syr
  namespace: et
spec:
  releaseName: et-syr
  values:
    nodejs:
      image: hmctsprod.azurecr.io/et/syr:pr-889-68b1442-20260528131721 #{"$imagepolicy": "flux-system:ithc-et-syr"}
      ingressHost: et-syr.ithc.platform.hmcts.net
      environment:
        HMCTS_ACCESS: 'true'
