apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: et-syr
  namespace: et
spec:
  releaseName: et-syr
  values:
    nodejs:
      image: hmctsprod.azurecr.io/et/syr:prod-b712e2d-20260703090749 #{"$imagepolicy": "flux-system:perftest-et-syr"}
      ingressHost: et-syr.perftest.platform.hmcts.net
      environment:
        ET3_LEGACY_URL: https://et-pet-et3.perftest.platform.hmcts.net/users/sign_up
