apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: et-syr
  namespace: et
spec:
  releaseName: et-syr
  values:
    nodejs:
      image: hmctsprod.azurecr.io/et/syr:prod-0c92dfa-20260323140854 #{"$imagepolicy": "flux-system:perftest-et-syr"}
      ingressHost: et-syr.perftest.platform.hmcts.net
