apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: et-syr
  namespace: et
spec:
  releaseName: et-syr
  values:
    nodejs:
      image: hmctsprod.azurecr.io/et/syr:prod-9051df1-20260727095705 #{"$imagepolicy": "flux-system:perftest-et-syr"}
      ingressHost: et-syr.perftest.platform.hmcts.net
      environment:
        HMCTS_ACCESS: 'true'