apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cath-web
spec:
  releaseName: cath-web
  interval: 5m
  install:
    remediation:
      retries: 3
    upgrade:
      remediation:
        strategy: uninstall
        retries: 3
  values:
    nodejs:
      releaseNameOverride: cath-web
      image: hmctsprod.azurecr.io/cath/cath-web:prod-50dd8da-20260904154025 # {"$imagepolicy": "flux-system:cath-web"}
  chart:
    spec:
      chart: cath-web
      version: ">=0.1.0-0"
      sourceRef:
        kind: HelmRepository
        name: hmctsprod-oci
        namespace: flux-system
      interval: 1m
