apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  annotations:
    hmcts.github.com/image-registry: hmctsprod
  name: cath-web
spec:
  image: hmctsprod.azurecr.io/cath/cath-web
