apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xui-case-activity-api
spec:
  releaseName: xui-case-activity-api
  values:
    nodejs:
      replicas: 2
      # This is to be updated once we have the new image available in perftest
      image: hmctsprod.azurecr.io/xui/case-activity-api:pr-1-ef2ad25-20260422181352 #{"$imagepolicy": "flux-system:demo-rpx-case-activity-api"}
      environment:
        DUMMY_VAR_TO_REDEPLOY: 2
