apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xui-case-activity-api
spec:
  releaseName: xui-case-activity-api
  values:
    nodejs:
      replicas: 2
      image: hmctsprod.azurecr.io/xui/case-activity-api:pr-1-6af8084-20260518141520 #{"$imagepolicy": "flux-system:perftest-rpx-case-activity-api"}
      environment:
        DUMMY_VAR_TO_REDEPLOY: 2
