apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: em-ccd-orchestrator
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/em/ccdorc:prod-f8b33e5-20260316081243 #{"$imagepolicy": "flux-system:demo-em-ccd-orchestrator"}
      environment:
        DUMMY_VAR: DELETE_ME-1
