apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: em-ccd-orchestrator
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/em/ccdorc:prod-1efe22f-20260330081130 #{"$imagepolicy": "flux-system:demo-em-ccd-orchestrator"}
      environment:
        DUMMY_VAR: DELETE_ME-1
