apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: em-ccd-orchestrator
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/em/ccdorc:pr-2323-1cd9fcd-20260715143639 #{"$imagepolicy": "flux-system:demo-em-ccd-orchestrator"}
      environment:
        IDAM_SECURITY_ALLOWED_ISSUERS_0: https://idam-web-public.demo.platform.hmcts.net/o
        IDAM_SECURITY_ALLOWED_ISSUERS_1: https://hmcts-access.demo.service.gov.uk/o
        IDAM_SECURITY_ALLOWED_ISSUERS_2: https://forgerock-am.service.core-compute-idam-demo.internal:8443/openam/oauth2/realms/root/realms/hmcts
        S2S_NAMES_WHITELIST: sscs,ccd,em_gw,ccd_data,iac,em_stitching_api,xui_webapp,civil_service,prl_cos_api,sptribs_case_api,et_cos,ethos_repl_service,civil_general_applications,finrem_citizen_ui
