apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fis-hmc-api
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/fis/hmc-api:pr-633-d36dd0e-20260527150412 #{"$imagepolicy": "flux-system:perftest-fis-hmc-api"}
      environment:
        DUMMY_VAR_TO_REDEPLOY: 2
