apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik2
  namespace: admin
spec:
  chart:
    spec:
      version: 40.2.0
  values:
    service:
      loadBalancerIP: "10.10.159.250"
    deployment:
      podLabels:
        useWorkloadIdentity: "true"
    serviceAccount:
      name: admin
