apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ia-case-access-api
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/ia/case-access-api:prod-78f4d1f-20260501144310 #{"$imagepolicy": "flux-system:ia-case-access-api"}
