apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: xui-mo-ogd-webapp
  annotations:
    hmcts.github.com/image-registry: hmctsprod
spec:
  image: hmctsprod.azurecr.io/xui/mo-webapp
