apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xui-mo-ogd-webapp
spec:
  releaseName: xui-mo-ogd-webapp
  values:
    nodejs:
      replicas: 2
      useInterpodAntiAffinity: true
      image: hmctsprod.azurecr.io/xui/mo-webapp:prod-c9e7f6a-20260826152307 #{"$imagepolicy": "flux-system:xui-mo-ogd-webapp"}
  chart:
    spec:
      chart: ./stable/xui-mo-webapp
      sourceRef:
        kind: GitRepository
        name: hmcts-charts
        namespace: flux-system
      interval: 1m
