apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fpl-cron-ccd-data-migration-tool
spec:
  releaseName: fpl-cron-ccd-data-migration-tool
  values:
    job:
      image: hmctsprod.azurecr.io/fpl/cron-ccd-data-migration-tool:prod-4ac523d-20260828110344 #{"$imagepolicy": "flux-system:demo-fpl-cron-ccd-data-migration-tool"}
      schedule: "30 12 30 2 *"
      environment:
        ENABLED: false
