apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../ccd-logstash-probateman
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: ccd-logstash-probateman
    patch: |-
      - op: replace
        path: /metadata/name
        value: ccd-elasticsearch-app-logstash-probateman
      - op: replace
        path: /spec/releaseName
        value: ccd-elasticsearch-app-logstash-probateman
