apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: em-stitching
spec:
  values:
    java:
      memoryRequests: "4608Mi"
      cpuRequests: "2000m"
      memoryLimits: "7168Mi"
      cpuLimits: "4000m"
      autoscaling:
        enabled: true
        maxReplicas: 4 # On each cluster
        cpu:
          averageUtilization: 85
        memory:
          averageUtilization: 85
      image: hmctsprod.azurecr.io/em/stitching:prod-959c6e1-20260601083735 #{"$imagepolicy": "flux-system:perftest-em-stitching"}
      environment:
        CALLBACK_MAX_ATTEMPTS: 1
        TEST_VAR: refresh
        HISTORIC_DOCUMENT_TASKS_NO_OF_RETENTION_DAYS: 180
        IDAM_SECURITY_ALLOWED_ISSUERS_0: https://idam-web-public.perftest.platform.hmcts.net/o
        IDAM_SECURITY_ALLOWED_ISSUERS_1: https://hmcts-access.perftest.platform.hmcts.net/o
        IDAM_SECURITY_ALLOWED_ISSUERS_2: https://forgerock-am.service.core-compute-idam-perftest.internal:8443/openam/oauth2/realms/root/realms/hmcts
