apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: deed-poll-api
spec:
  values:
    java:
      environment:
        IDAM_API_ISSUER_URL: https://hmcts-access.aat.platform.hmcts.net/o
        IDAM_API_AUDIENCES: deed-poll-admin
