apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sptribs-case-api
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/sptribs/case-api:pr-2534-4c60d68-20260609171937 #{"$imagepolicy": "flux-system:demo-sptribs-case-api"}
      environment:
        S2S_AUTHORISED_SERVICES: ccd_definition,ccd_data,xui_webapp,sptribs_case_api,ccd_gw,sptribs_frontend,sptribs_dss_update_case_web
        WA_FEATURE_ENABLED: true
        PSEUDO_VAR: 1
        TASK_MONITOR_API_URL: http://wa-task-monitor-demo.service.core-compute-demo.internal
        TASK_MANAGEMENT_API_URL: http://wa-task-management-api-demo.service.core-compute-demo.internal
        ROLE_ASSIGNMENT_API_URL: http://am-org-role-mapping-service-demo.service.core-compute-demo.internal
