apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sptribs-case-api
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/sptribs/case-api:prod-56af042-20260722121920 #{"$imagepolicy": "flux-system:ithc-sptribs-case-api"}
      environment:
        IDAM_WEB_URL: https://idam-web-public.ithc.platform.hmcts.net/login
        S2S_AUTHORISED_SERVICES: ccd_definition,ccd_data,xui_webapp,sptribs_case_api,ccd_gw,sptribs_frontend,sptribs_dss_update_case_web
        WA_FEATURE_ENABLED: true
