apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: probate-cron-caveat-expiry
spec:
  releaseName: probate-cron-caveat-expiry
  values:
    job:
      image: hmctsprod.azurecr.io/probate/back-office:pr-3693-03b9cbb-20260605103214 #{"$imagepolicy": "flux-system:demo-probate-back-office"}
      schedule: "0 16 18 6 *"
      environment:
        TASK_NAME: CaveatExpiryTask
        ADHOC_JOB_DATE: "2026-11-27"
    global:
      jobKind: CronJob
      enableKeyVaults: true
      tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
      environment: demo
