apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: em-npa
spec:
  values:
    java:
      image: hmctspublic.azurecr.io/em/npa:prod-4ce3c9e-20260309155959 #{"$imagepolicy": "flux-system:demo-em-npa"}
      environment:
        TEST_VAR: refresh2
