apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sscs-tribunals-frontend
  namespace: sscs
spec:
  values:
    nodejs:
      ingressHost: www.appeal-benefit-decision.service.gov.uk
      registerAdditionalDns:
        enabled: true
        prefix: appeal
        primaryIngressHost: infected-blood-compensation-decision.service.gov.uk
      livenessPath: /health/readiness
      environment:
        CONTACT_US_WEB_FORM_ENABLED: false
        SERVICES_IDAM_LOGIN_URL: https://hmcts-access.service.gov.uk/login
        SERVICES_IDAM_API_URL: https://idam-api.platform.hmcts.net
        PCQ_URL: https://equality-and-diversity.platform.hmcts.net
        PCQ_ENABLED: "true"
        FT_ALLOW_UC_HEARING_OPTIONS: "true"
        MEDIA_FILES_ALLOWED_ENABLED: "true"
        ALLOW_DLA_ENABLED: "true"
        ALLOW_CA_ENABLED: "true"
        ALLOW_AA_ENABLED: "true"
        ALLOW_BB_ENABLED: "true"
        ALLOW_IIDB_ENABLED: "true"
        ALLOW_JSA_ENABLED: "true"
        ALLOW_MA_ENABLED: "true"
        ALLOW_BSPS_ENABLED: "true"
        ALLOW_IDB_ENABLED: "true"
        ALLOW_PC_ENABLED: "true"
        ALLOW_RP_ENABLED: "true"
        ALLOW_SF_ENABLED: "true"
        ALLOW_IS_ENABLED: "true"
        ALLOW_RFE_ENABLED: "true"
        MULTIPLE_DRAFTS_ENABLED: "true"
        DUMMY_PROPERTY: "false"
        IBC_NI_POSTCODES_FEATURE: true
