apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plum-frontend
spec:
  chart:
    spec:
      chart: ./stable/plum-frontend
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: hmcts-charts
        namespace: flux-system
  values:
    nodejs:
      ingressHost: plum.sandbox.platform.hmcts.net
      replicas: 2
      autoscaling:
        minReplicas: 1
      image: hmctssbox.azurecr.io/plum/frontend:prod-70b5ac7-20260514111334 # {"$imagepolicy": "flux-system:plum-frontend-sbox"}
