apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rota-resource
spec:
  releaseName: rota-resource
  values:
    java:
      ingressHost: rota-resource-aat.service.core-compute-aat.internal
