apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cui-ra
spec:
  values:
    nodejs:
      image: hmctsprod.azurecr.io/cui/ra:prod-8751e25-20260729165938 #{"$imagepolicy": "flux-system:ithc-cui"}
