apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cui-ra
spec:
  values:
    nodejs:
      image: hmctsprod.azurecr.io/cui/ra:prod-0227cc9-20260917143653 #{"$imagepolicy": "flux-system:ithc-cui"}
