apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cui-ra
spec:
  values:
    nodejs:
      image: hmctsprod.azurecr.io/cui/ra:prod-509cc49-20260817091359 #{"$imagepolicy": "flux-system:ithc-cui"}
