apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ccd-export
spec:
  values:
    base:
      image: hmctsprod.azurecr.io/et-pet/ccd-export:prod-cb92e0e-20260804082619 #{"$imagepolicy": "flux-system:demo-et-pet-ccd-export"}
