apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ccd-export
spec:
  values:
    base:
      image: hmctsprod.azurecr.io/et-pet/ccd-export:pr-413-55b1c12-20260805123637 #{"$imagepolicy": "flux-system:demo-et-pet-ccd-export"}
