apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${NAMESPACE}
  namespace: ${NAMESPACE}
  annotations:
    azure.workload.identity/client-id: "cda48b12-c4c3-480c-9bd4-2565d001d3a7"
automountServiceAccountToken: false
