apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: ../../serviceaccount/sbox.yaml
  - path: fluentbit-log-patch.yaml
  # - path: neuvector-delete-patch.yaml
