apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ccd-logstash
  namespace: ccd
spec:
  releaseName: ccd-logstash
  values:
    replicas: 1
    extraEnvs:
      - name: ES_HOST0
        value: http://ccd-data-0.service.core-compute-ithc.internal:9200
      - name: ES_HOST1
        value: http://ccd-data-1.service.core-compute-ithc.internal:9200
      - name: ES_HOST2
        value: http://ccd-data-2.service.core-compute-ithc.internal:9200
      - name: ES_HOST3
        value: http://ccd-data-3.service.core-compute-ithc.internal:9200
