apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pcs-frontend
spec:
  releaseName: pcs-frontend
  values:
    nodejs:
      replicas: 2
      memoryLimits: "1024Mi"
      memoryRequests: "512Mi"
      cpuLimits: "1500m"
      cpuRequests: "500m"
      image: hmctsprod.azurecr.io/pcs/frontend:prod-a25f612-20260908173204 #{"$imagepolicy": "flux-system:pcs-frontend"}
      environment:
        TRIGGER_VAR: 1
  chart:
    spec:
      chart: ./stable/pcs-frontend
      sourceRef:
        kind: GitRepository
        name: hmcts-charts
        namespace: flux-system
      interval: 1m
