apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pcs-frontend
spec:
  values:
    nodejs:
      cpuRequests: "250m"
      cpuLimits: "1000m"
      memoryRequests: "512Mi"
      memoryLimits: "1024Mi"
