apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: case-payment-orders-api-int
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/cpo/case-payment-orders-api:prod-76da7be-20260714160325 #{"$imagepolicy": "flux-system:case-payment-orders-api"}
