apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: case-payment-orders-api-int
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/cpo/case-payment-orders-api:prod-522da56-20260324171244 #{"$imagepolicy": "flux-system:case-payment-orders-api"}
