apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wa
resources:
- ../base
patches:
- path: ../../wa-task-batch-reconfiguration/ithc.yaml
- path: ../../wa-task-batch-termination/ithc.yaml
- path: ../../wa-task-batch-initiation/ithc.yaml
- path: ../../wa-task-batch-update-search-index/ithc.yaml
- path: ../../wa-task-batch-replication-check/ithc.yaml
- path: ../../wa-task-batch-reconfiguration-failure/ithc.yaml
- path: ../../wa-task-batch-termination-failure/ithc.yaml
- path: ../../wa-task-batch-initiation-failure/ithc.yaml
