apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: aat-civil-citizen-ui-postgresql
  annotations:
    hmcts.github.com/prod-automated: disabled
spec:
  filterTags:
    pattern: '^(?P<version>17\.5\.0-debian-12-r20)$'
    extract: '$version'
  policy:
    alphabetical:
      order: asc
  imageRepositoryRef:
    name: aat-civil-citizen-ui-postgresql