apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: aat-civil-citizen-ui-postgresql
  annotations:
    hmcts.github.com/image-registry: hmctsprod
spec:
  image: hmctsprod.azurecr.io/imported/bitnami/postgresql