apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: civil-citizen-ui
  namespace: civil
spec:
  values:
    nodejs:
      replicas: 2
      readinessDelay: 45
      readinessTimeout: 5
      readinessPeriod: 15
      useInterpodAntiAffinity: true
      image: hmctsprod.azurecr.io/civil/citizen-ui:prod-9396258-20261007124350 #{"$imagepolicy": "flux-system:civil-citizen-ui"}
      environment:
        TEMP_VAR: 1
        IDAM_API_URL: https://idam-web-public.aat.platform.hmcts.net/o/token
        IDAM_WEB_URL: https://idam-web-public.aat.platform.hmcts.net/o/authorize
    aac-manage-case-assignment:
      java:
        image: hmctsprod.azurecr.io/aac/manage-case-assignment:prod-2d381c9-20260925091953 #{"$imagepolicy": "flux-system:aat-civil-citizen-ui-aac-manage-case-assignment"}
    xui-webapp:
      nodejs:
        image: hmctsprod.azurecr.io/xui/webapp:prod-b64761b-20261007140443 #{"$imagepolicy": "flux-system:aat-civil-citizen-ui-xui-webapp"}
    ccd-api-gateway-web:
      nodejs:
        image: hmctsprod.azurecr.io/ccd/api-gateway-web:prod-558e628-20261006085447 #{"$imagepolicy": "flux-system:aat-civil-citizen-ui-ccd-api-gateway-web"}
    postgresql:
      image:
        tag: 17.5.0-debian-12-r20 #{"$imagepolicy": "flux-system:aat-civil-citizen-ui-postgresql:tag"}
