apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: civil-citizen-ui
  namespace: civil
spec:
  values:
    nodejs:
      replicas: 2
      readinessDelay: 45
      readinessTimeout: 5
      readinessPeriod: 15
      useInterpodAntiAffinity: true
      image: hmctsprod.azurecr.io/civil/citizen-ui:prod-281f43b-20260902090116 #{"$imagepolicy": "flux-system:civil-citizen-ui"}
      environment:
        TEMP_VAR: 1
        IDAM_API_URL: https://hmcts-access.aat.platform.hmcts.net/o/token
        IDAM_WEB_URL: https://hmcts-access.aat.platform.hmcts.net/o/authorize
