apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: civil-citizen-ui
  namespace: civil
spec:
  values:
    nodejs:
      replicas: 2
      readinessDelay: 45
      readinessTimeout: 5
      readinessPeriod: 15
      useInterpodAntiAffinity: true
      image: hmctsprod.azurecr.io/civil/citizen-ui:prod-999d8ca-20260722111343 #{"$imagepolicy": "flux-system:civil-citizen-ui"}
      environment:
        TEMP_VAR: 1
