apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apim-marketplace-examples
spec:
  values:
    java:
      ingressHost: apim-marketplace-examples.sandbox.platform.hmcts.net
      environment:
        APPLICATIONINSIGHTS_ENABLED: "false"
        APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=00000000-0000-0000-0000-000000000000"
