apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: civil-sdt-gateway
  namespace: civil
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/civil/sdt-gateway:prod-cbb6664-20260326154311 #{"$imagepolicy": "flux-system:demo-civil-sdt-gateway"}
