apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: civil-sdt-gateway
  namespace: civil
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/civil/sdt-gateway:prod-1ddb4d0-20260330124153 #{"$imagepolicy": "flux-system:demo-civil-sdt-gateway"}
