apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prl-cron-request-order-task
spec:
  releaseName: prl-cron-request-order-task
  values:
    job:
      ingressClass: traefik-private
      image: hmctspublic.azurecr.io/prl/cos:prod-76bf995-20241216170533 #{"$imagepolicy": "flux-system:ithc-prl-cron-request-order-task"}
      environment:
        APP_ENV: "ithc"
        TASK_NAME: RequestOrderTask
        IDAM_CLIENT_REDIRECT_URI: https://prl-cos-demo.service.core-compute-demo.internal/oauth2/callback
        IDAM_API_URL: https://idam-api.demo.platform.hmcts.net
        IDAM_S2S_AUTH_URL: http://rpe-service-auth-provider-demo.service.core-compute-demo.internal
        CORE_CASE_DATA_API_URL: http://ccd-data-store-api-demo.service.core-compute-demo.internal
        AUTH_IDAM_CLIENT_BASEURL: https://idam-api.demo.platform.hmcts.net
        AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: http://rpe-service-auth-provider-demo.service.core-compute-demo.internal
        PRL_S2S_AUTHORISED_SERVICES: api_gw,prl_citizen_frontend,fis_hmc_api,ccd_data,payment_app
        REFDATA_API_URL: http://rd-commondata-api-demo.service.core-compute-demo.internal
        AM_ROLE_ASSIGNMENT_API_URL: http://am-role-assignment-service-demo.service.core-compute-demo.internal
        HEARING_API_BASEURL: http://fis-hmc-api-demo.service.core-compute-demo.internal
      schedule: 0/10 * * * *
    global:
      jobKind: CronJob
      enableKeyVaults: true
      tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
      environment: ithc
