apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: am-org-role-mapping-service
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/am/org-role-mapping-service:prod-c777584-20260925142602 #{"$imagepolicy": "flux-system:ithc-am-org-role-mapping-service"}
      environment:
        AM_INFO: true
        APPLICATION_LOGGING_LEVEL: INFO
        DB_FEATURE_FLAG_ENABLE: iac_wa_1_8
        TESTING_SUPPORT_ENABLED: false
        # PRD Config
        PROFESSIONAL_REFRESH_API_ENABLED: true
        PROFESSIONAL_SCHEDULING_ENABLED: true
        # PRM Schedules
        # PRM-1
        CRON_PRM_P1_FIND_CASE_DEFINITION_CHANGES: "0 00 8 * * MON-FRI"
        CRON_PRM_P1_LOCK_AT_LEAST_FOR: "PT1M"
        CRON_PRM_P1_LOCK_AT_MOST_FOR: "PT5M"
        # PRM-2
        CRON_PRM_P2_ORGS_STALE_PROFILES: "0 05 8 * * MON-FRI"
        CRON_PRM_P2_LOCK_AT_LEAST_FOR: "PT1M"
        CRON_PRM_P2_LOCK_AT_MOST_FOR: "PT5M"
        # PRM-3
        CRON_PRM_P3_ORG_CHANGES: "0 10 8 * * MON-FRI"
        CRON_PRM_P3_LOCK_AT_LEAST_FOR: "PT10M"
        CRON_PRM_P3_LOCK_AT_MOST_FOR: "PT30M"
        # PRM-4
        CRON_PRM_P4_USERS_STALE_ORGS: "0 30 8 * * MON-FRI"
        CRON_PRM_P4_LOCK_AT_LEAST_FOR: "PT20M"
        CRON_PRM_P4_LOCK_AT_MOST_FOR: "PT30M"
        # PRM-5
        CRON_PRM_P5_USER_CHANGES: "0 00 9 * * MON-FRI"
        CRON_PRM_P5_LOCK_AT_LEAST_FOR: "PT5M"
        CRON_PRM_P5_LOCK_AT_MOST_FOR: "PT30M"
        # PRM-6
        CRON_PRM_P6_USER_REFRESH: "0 15 9 * * MON-FRI"
        CRON_PRM_P6_LOCK_AT_LEAST_FOR: "PT30M"
        CRON_PRM_P6_LOCK_AT_MOST_FOR: "PT180M"
        # PRM-Cleanup Org
        CRON_PRM_REFRESH_CLEANUP_ORG: "-"
        # PRM-Cleanup User
        CRON_PRM_REFRESH_CLEANUP_USER: "-"
        # Refresh Job Config
        REFRESH_JOB: LEGAL_OPERATIONS-IA-NEW-0-9
        # always set 'REFRESH_JOB_ALLOW_UPDATE' to false before next refresh (i.e. only use when setting existing job to ABORTED)
        # REFRESH_JOB_ALLOW_UPDATE: false
        # Other
        DUMMY_VAR: false
