apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: am-org-role-mapping-service
spec:
  values:
    java:
      image: hmctsprod.azurecr.io/am/org-role-mapping-service:prod-a50b51c-20260603154305 #{"$imagepolicy": "flux-system:perftest-am-org-role-mapping-service"}
      environment:
        AM_INFO: false
        APPLICATION_LOGGING_LEVEL: INFO
        DB_FEATURE_FLAG_ENABLE: possessions_wa_1_0
        # PRD Config
        PROFESSIONAL_REFRESH_API_ENABLED: false
        PROFESSIONAL_SCHEDULING_ENABLED: false
        # Refresh Job Config
        # REFRESH_JOB: LEGAL_OPERATIONS-ST_CIC-NEW-0-113
        # always set 'REFRESH_JOB_ALLOW_UPDATE' to false before next refresh (i.e. only use when setting existing job to ABORTED)
        # REFRESH_JOB_ALLOW_UPDATE: false
        # REFRESH_BULK_ASSIGNMENT_INCLUDE_BOOKINGS: true
        # Other
        DUMMY_VAR: false
