apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aac-ac-int-manage-case-assignment
spec:
  releaseName: aac-ac-int-manage-case-assignment
  values:
    java:
      image: hmctsprod.azurecr.io/aac/manage-case-assignment:prod-6d1165f-20260319181119 #{"$imagepolicy": "flux-system:manage-case-assignment"}
