apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sptribs-dss-update-case-web
  namespace: sptribs
spec:
  values:
    nodejs:
      image: hmctsprod.azurecr.io/sptribs/dss-update-case-web:pr-1178-70ed91c-20260515143421
      ingressSessionAffinity:
        enabled: true
        sessionCookieName: sticky
    global:
      environment: ithc
      IDAM_API_URL: https://idam-web-public.ithc.platform.hmcts.net/o/token
      IDAM_WEB_URL: https://idam-web-public.ithc.platform.hmcts.net/o/authorize
      enableKeyVaults: true
