apiVersion: v1
data:
    apiToken: ENC[AES256_GCM,data:TUIe20+9F7y47XVby+yj9O1JapsXRqUEE/T4CLgCDBNimVZNTTPElQ2Z1sEnSvUkxwVgKhhN2sTRNC1ejt279hO+nbjLxTQVmnG9mgstkOJJMwxZ+vgqO4/rl4Id0WsTWif4MQoJS2fCvvuDpZORw6SvkQailWoFuefBxc5GZ44=,iv:Ie185sHJHDK1Vmg+3xz4G0OMJ2jY9HM/Jd7HJG2QFtM=,tag:VWJDmfIX/nRWzC1PzRadhA==,type:str]
    dataIngestToken: ENC[AES256_GCM,data:683lAFp29DVstm+cIYVYa7sdcG+nxxVCm/KU0u+NZES2+aFoVEn9Louelg3E6tZK0hTdlJD+D93pRX+IJc5SG0236tCttLPJivQVNcF79enm2iT2QNsKiEwbTJJ9jz80/yE3Bsz39JnlZQ1/O+QAy+J6rkeNM1DpkHH/IVNMivg=,iv:tt8RTC8hB8eADoYJm88+AOBhK5SHX1UbmI2WN2i3NnY=,tag:7rwAezB/SsuHOTFOo9KQNw==,type:str]
kind: Secret
metadata:
    name: dynakube
    namespace: dynatrace
type: Opaque
sops:
    azure_kv:
        - vault_url: https://dcdcftappsdevkv.vault.azure.net
          name: sops-key
          version: aedb9ea38954430ca1d0a46ed589c049
          created_at: "2026-07-29T07:46:07Z"
          enc: QtDdvmaixzsDzq9CoYBUKDaSoqggnZJXBej8_lI86MrifYBpG3IzHeReqThz9EN83CQzhmIurZHxFz8dQwqxqJXH3_AMPlOqjt9KmckDXlLxC5yi9u0hjSy35mTTQa1iF1AJ-DnVpFOl6XGoB9aBvg70NCj6m0A6Qr6neGhailXtq6CocAUyO_5J6XNh5UXe32wtQnVGQ-5tLHNUlNmn41wPQo28r0wF3Mc2-HYu-uLc8gE_OJQMNvjZ1MU1AjDC--bhYdx-vyWGodvBc5nV53SZtj7MI88uovwVPF0K0VGch3Q5TwiJM8rTz0j3iU1ATZtkANtadfqnGpFVWGnUfA
    lastmodified: "2026-07-29T07:46:09Z"
    mac: ENC[AES256_GCM,data:e7MbnMFVuCTXUMkiIxLpmJC3Fm/nGndN8fwdFIloYFtmswLqnME0rcuI9UGBl2a6SG1O+zxmHBpg96cgxnYCGVLOq/skNYxO4hiv+jDPqG0R8RQdIBkP9JqVkd9mCm3TVQmMCkzJ5rcDSrdFuMgxFl7QRCAnCv21b/tLQOpDmqw=,iv:22TFZWtY9WD+SJKA4QKbwqFGqi7099nTdqpCMaczPAo=,tag:KpLMuBdUbMajF5TnHV3tFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
