apiVersion: v1
data:
    apiToken: ENC[AES256_GCM,data:0Ux91zFMDIINSxBHG+01UKINi5cibw3GqPNNpd8VwzdTQO9bIHorR5S3vhzOO65smoEIbiJg0XpRtNfA5jqc917mYzKk9Enp+lFogb4+xqewE0HmghDU+/DttZirdUA3ayVfIrLvyiVeTXPfrUpTAqJwu1hFwaKgfULm2IkfVxw=,iv:OL+3F3iH5tqwGq1lR0/S0oEyfGYSCL1WaT5j5A94f3I=,tag:7LZoVLZCxbR0xp0sytj6Hw==,type:str]
    dataIngestToken: ENC[AES256_GCM,data:dJAS1EUs+OV2caxiTOaWEPxyam6oBeGOHcs/VIAag2TxQDul/SWyDy4UgvTbLYnySqSlzKKTLu1bqk9DGhTRcfG7Z84m+VZfpKHLdrhTBsA+cZJDLpxBs1975TlJkSSD4bjpDrvH8R7UqpCYO7zyPFwjr1qfdyTCWL5rXDVELGo=,iv:caItP7DfhZlzvU7qmZCQPsfRwoIyR/dC+e621L5fXkM=,tag:ShW6kJx48U75oQHSBSF1eA==,type:str]
kind: Secret
metadata:
    name: dynakube
    namespace: dynatrace
type: Opaque
sops:
    azure_kv:
        - vault_url: https://dcdcftappsdevkv.vault.azure.net
          name: sops-key
          version: aedb9ea38954430ca1d0a46ed589c049
          created_at: "2023-02-15T13:05:07Z"
          enc: MyysmULTMjvr80Fp5-LynQBdA31mny_MRPr6WCTLLqdPP8TzO80Y1BCAgxTmm9GqYPtF6Dmi4MzufriArbCwOLTg3vqB06epRnxuzzfPjiq2BbuFN-QB5ry-cykbrQbpD2lkS-idvo4nCz7Jc9P9vpScfzZsKXgUQWJpY9AJhEOLRC6J-iBwXmuMd_55sLqfJ25Oxh0CCarXu_KQMWk6k2FSlpo83bUc8mnkZpvqX-FlwIPA35zY8WtFQrXEgE4XvqTsxEsBPO9y3RagxS2KN8YQpVJh2_sbaAOsX956awINVLwgzS5PCHjNG6alEJlPCTzYWo4sKA7U6nRyKLteoA
    lastmodified: "2026-06-15T13:04:19Z"
    mac: ENC[AES256_GCM,data:g+fvG3flBaLB1NL12bvpcb2GupAk+t8MmbogR2L8WIV60f3l+1vGOAvyURac3Q559AOclhcrs31osWOL6S86CLGGrwEi4MVd9PH5Imcjbnpnst4u4u3+WWgM7RnU16FIcvkjp5gZSFYS40VmJX2i7g8553sgDP9JCw+FFBZUkZQ=,iv:a6c9haZKt8Lo+99e8LYGcZbjSNFvuickfBbUHDM4PlM=,tag:x12xbRrLqfGRZVq1Xk+0PQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
