apiVersion: v1
data:
    apiToken: ENC[AES256_GCM,data:Stct3CFEp3DSn8rhhBlro46JeF22sBaILUvoQBVPnaUBbm5vHdqG5U7EJ7XDa5+g50s6CzffPZxsrmxNDnldTq4YHkW56jI8k50K44mb708dAq6rfeItyDUZY+EOvl7IVtolD/+0oaqLbg7Le5o17t7o2cEPUzKVPRDqCRYaQbc=,iv:2DIDI+A3bWZa57A6ZgHeRhkaZRQyb2ziHZxa579/ZEY=,tag:FM4e67cSnr2lxo9EL/P03Q==,type:str]
    dataIngestToken: ENC[AES256_GCM,data:rT/vV+aLCJYb9b4duTeA/xLvFD+gv7Js7xMwseHcdGThZRbmEwY8asS/lBCK/tZwHaM0BEwvVJJgdo+GjFXZhO7sWVBmsEmTgqrSHIrXKegyVjLrbLVZWvs80uf9D3d2sWFzAT6NeKoQrSqFpioUFPmG4ID+Bh/oHROpgOiMrcA=,iv:+Gh9jo4LMygB/AxjeuquS1DwBxeKXS3qvwZlsrYYNIE=,tag:JlVeCXKmZ3Ves+G1UWHNdA==,type:str]
kind: Secret
metadata:
    name: dynakube
    namespace: dynatrace
type: Opaque
sops:
    azure_kv:
        - created_at: "2026-07-29T07:46:07Z"
          enc: QtDdvmaixzsDzq9CoYBUKDaSoqggnZJXBej8_lI86MrifYBpG3IzHeReqThz9EN83CQzhmIurZHxFz8dQwqxqJXH3_AMPlOqjt9KmckDXlLxC5yi9u0hjSy35mTTQa1iF1AJ-DnVpFOl6XGoB9aBvg70NCj6m0A6Qr6neGhailXtq6CocAUyO_5J6XNh5UXe32wtQnVGQ-5tLHNUlNmn41wPQo28r0wF3Mc2-HYu-uLc8gE_OJQMNvjZ1MU1AjDC--bhYdx-vyWGodvBc5nV53SZtj7MI88uovwVPF0K0VGch3Q5TwiJM8rTz0j3iU1ATZtkANtadfqnGpFVWGnUfA
          name: sops-key
          vault_url: https://dcdcftappsdevkv.vault.azure.net
          version: aedb9ea38954430ca1d0a46ed589c049
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T13:16:25Z"
    mac: ENC[AES256_GCM,data:G4oTXJxKPI3wA36AUUYH2QvvuirpSje3Mv3dBbLHsk2laciaU9Ya3qUI9KoM7Nl90BwBzIaUi++LyRbfZazybFxAFgS8XAie1q+c7IR2V2+yifoYLFTQVDRRbsVQjD2IrFk2t0o6ugELZ3d91H+8i9DVBjH6gpOy2b/9WoJlVCc=,iv:+iv/KVEW/pt1ntr7VQlFjoK705GZoqtHl9WGGJcT9XE=,tag:YcQtLkg9c1rsQAa/SYHKYA==,type:str]
    version: 3.13.3
