apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: et3
spec:
  releaseName: et3
  values:
    base:
      image: hmctsprod.azurecr.io/et-pet/et3:prod-801ae8a-20261001141718 #{"$imagepolicy": "flux-system:et-pet-et3"}
  chart:
    spec:
      chart: ./stable/et-pet-et3
      sourceRef:
        kind: GitRepository
        name: hmcts-charts
        namespace: flux-system
      interval: 1m
